from dataclasses import dataclass
from typing import Callable

from .synthetic_param_cases import (
    validate_synthetic_history_ev_threshold_case,
    validate_synthetic_lookahead_prev_day_only_case,
    validate_synthetic_param_guardrail_case,
    validate_synthetic_pit_multiple_same_day_exits_case,
    validate_synthetic_pit_same_day_exit_excluded_case,
    validate_synthetic_portfolio_history_filter_only_case,
    validate_synthetic_proj_cost_cash_capped_case,
    validate_synthetic_single_backtest_uses_compounding_capital_case,
    validate_synthetic_single_backtest_not_gated_by_own_history_case,
    validate_use_compounding_failfast_guardrail_case,
)
from .synthetic_history_cases import (
    validate_synthetic_setup_index_prev_day_only_case,
)
from .synthetic_portfolio_cases import (
    validate_synthetic_candidate_order_fill_layer_separation_case,
    validate_synthetic_portfolio_entry_preserves_fill_based_first_actionable_case,
    validate_synthetic_competing_candidates_case,
    validate_synthetic_conservative_executable_exit_interpretation_case,
    validate_synthetic_exit_orders_only_for_held_positions_case,
    validate_synthetic_extended_miss_buy_case,
    validate_synthetic_extended_signal_a2_frozen_plan_case,
    validate_synthetic_init_sl_single_source_runtime_case,
    validate_synthetic_fee_tax_net_equity_case,
    validate_synthetic_half_tp_full_year_case,
    validate_synthetic_intraday_reprice_forbidden_case,
    validate_synthetic_missed_buy_no_replacement_case,
    validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case,
    validate_synthetic_missed_sell_accounting_case,
    validate_synthetic_no_intraday_switch_after_failed_fill_case,
    validate_synthetic_rotation_t_plus_one_case,
    validate_synthetic_round_trip_pnl_only_on_tail_exit_case,
    validate_synthetic_same_bar_stop_priority_case,
    validate_synthetic_same_day_buy_sell_forbidden_case,
    validate_synthetic_same_day_sell_block_case,
    validate_synthetic_unexecutable_half_tp_case,
)
from .synthetic_unit_cases import (
    validate_exact_accounting_cash_risk_boundary_case,
    validate_exact_accounting_cost_basis_allocation_case,
    validate_exact_accounting_display_derived_case,
    validate_exact_accounting_display_leg_reconciliation_case,
    validate_exact_accounting_ledger_conservation_case,
    validate_exact_accounting_single_vs_portfolio_parity_case,
    validate_exact_accounting_tick_limit_integer_case,
    validate_history_filters_unit_case,
    validate_independent_oracle_golden_case,
    validate_portfolio_stats_unit_case,
    validate_price_utils_unit_case,
    validate_signal_utils_unit_case,
)
from .synthetic_meta_cases import (
    validate_checklist_t_formal_command_single_entry_case,
    validate_checklist_done_test_summary_markdown_structure_case,
    validate_checklist_t_single_entry_delimiter_case,
    validate_checklist_g_transition_format_case,
    validate_checklist_g_ordering_case,
    validate_checklist_g_new_transition_first_occurrence_case,
    validate_checklist_g_transition_sequence_case,
    validate_checklist_summary_tables_sorted_by_id_case,
    validate_synthetic_cases_import_target_resolution_contract_case,
    validate_quick_gate_synthetic_registry_import_targets_contract_case,
    validate_price_utils_array_tick_normalization_contract_case,
    validate_test_suite_help_text_mentions_stable_theme_tokens_case,
    validate_portfolio_rotation_mark_to_market_return_contract_case,
    validate_portfolio_core_module_boundary_contract_case,
    validate_debug_backtest_entry_cash_path_contract_case,
    validate_single_backtest_stats_legacy_schema_contract_case,
    validate_cmd_document_contract_case,
    validate_core_trading_modules_in_coverage_targets_case,
    validate_critical_helper_single_source_contract_case,
    validate_policy_contract_modules_in_coverage_targets_case,
    validate_meta_quality_coverage_threshold_uses_target_scope_case,
    validate_coverage_threshold_floor_case,
    validate_critical_coverage_threshold_floor_case,
    validate_critical_file_coverage_minimum_gate_case,
    validate_entry_path_critical_coverage_gate_case,
    validate_formal_step_entry_coverage_targets_case,
    validate_formal_step_implementation_coverage_targets_case,
    validate_known_bad_fault_injection_case,
    validate_no_legacy_app_entry_doc_references_case,
    validate_app_thin_wrapper_export_contract_case,
    validate_no_reverse_app_layer_dependencies_case,
    validate_no_top_level_import_cycles_case,
    validate_peak_traced_memory_tracker_context_management_case,
    validate_checklist_physical_trading_principles_contract_case,
    validate_specific_pass_only_exception_traceability_contract_case,
    validate_broad_exception_traceability_contract_case,
    validate_gui_tcl_fallback_traceability_contract_case,
    validate_gui_workbench_documentation_sync_case,
    validate_architecture_workbench_entry_file_tree_sync_case,
    validate_model_param_source_resolution_contract_case,
    validate_architecture_local_regression_meta_quality_file_tree_sync_case,
    validate_trade_analysis_legacy_naming_documentation_contract_case,
    validate_trade_analysis_canonical_alias_export_contract_case,
    validate_validate_runtime_tmp_output_staging_contract_case,
    validate_optional_dependency_fallback_traceability_contract_case,
    validate_registry_checklist_entry_consistency_case,
    validate_single_formal_test_entry_contract_case,
    validate_synthetic_registry_metadata_contract_case,
    validate_test_suite_orchestrator_coverage_targets_case,
)
from .synthetic_breakout_quality_policy_cases import (
    validate_breakout_quality_policy_single_source_case,
    validate_breakout_quality_active_legacy_model_isolation_contract_case,
    validate_breakout_quality_chronological_embargo_case,
)
from .synthetic_breakout_quality_artifact_cases import (
    validate_breakout_quality_runtime_artifact_contract_case,
)
from .synthetic_breakout_quality_model_cases import (
    validate_breakout_quality_continuous_target_contract_case,
    validate_breakout_quality_continuous_ranker_contract_case,
    validate_breakout_quality_all_event_no_time_ranker_contract_case,
    validate_breakout_quality_pairwise_ranker_contract_case,
    validate_breakout_quality_daily_full_list_ndcg_pairwise_contract_case,
    validate_breakout_quality_full_horizon_target_components_contract_case,
    validate_breakout_quality_reusable_model_component_contract_case,
    validate_breakout_quality_low_adverse_target_component_contract_case,
    validate_breakout_quality_multi_dl_ranker_architecture_contract_case,
)
from .synthetic_breakout_quality_audit_cases import (
    validate_breakout_quality_audit_framework_contract_case,
)
from .synthetic_breakout_quality_pit_cases import (
    validate_breakout_quality_point_in_time_score_builder_contract_case,
    validate_breakout_quality_selection_point_in_time_score_sort_contract_case,
)
from .synthetic_breakout_quality_strategy_cases import (
    validate_breakout_quality_strategy_comparison_contract_case,
    validate_breakout_quality_binary_dl_param_adaptation_contract_case,
    validate_breakout_quality_trade_path_label_contract_case,
    validate_breakout_quality_legacy_research_cleanup_contract_case,
    validate_breakout_quality_strategy_readable_report_contract_case,
)
from .synthetic_breakout_quality_strategy_app_cases import (
    validate_breakout_quality_single_seed_single_entry_contract_case,
    validate_strategy_compare_config_driven_app_contract_case,
    validate_breakout_quality_daily_pit_strategy_runtime_contract_case,
    validate_breakout_quality_runtime_integration_gate_contract_case,
)
from .synthetic_breakout_quality_strategy_plan_cases import (
    validate_strategy_compare_resolved_plan_transition_contract_case,
)
from .synthetic_display_cases import validate_display_reporting_sanity_case
from .synthetic_reporting_cases import (
    validate_issue_excel_report_schema_case,
    validate_portfolio_export_report_artifacts_case,
    validate_portfolio_yearly_report_schema_case,
    validate_test_suite_summary_checklist_status_sync_case,
    validate_test_suite_summary_dataset_prepare_failure_reporting_case,
    validate_test_suite_summary_failure_reporting_case,
    validate_test_suite_summary_manifest_failure_reporting_case,
    validate_test_suite_summary_meta_quality_guardrail_reporting_case,
    validate_test_suite_summary_meta_quality_memory_reporting_case,
    validate_test_suite_summary_optional_dataset_skip_case,
    validate_test_suite_summary_preflight_failure_reporting_case,
    validate_test_suite_summary_reporting_case,
    validate_test_suite_summary_unreadable_payload_reporting_case,
    validate_validate_console_summary_reporting_case,
)
from .synthetic_contract_cases import (
    validate_artifact_lifecycle_contract_case,
    validate_atomic_write_contract_case,
    validate_atomic_write_retry_contract_case,
    validate_atomic_write_cleanup_error_preserves_root_exception_case,
    validate_validate_summary_atomic_write_contract_case,
    validate_dataset_fingerprint_contract_case,
    validate_reduced_dataset_dynamic_contract_case,
    validate_run_all_dataset_prepare_pass_main_contract_case,
    validate_local_regression_summary_contract_case,
    validate_meta_quality_reuses_existing_coverage_artifacts_case,
    validate_debug_trade_log_chart_context_optional_case,
    validate_debug_trade_log_prepared_tool_contract_case,
    validate_debug_chart_payload_without_html_export_contract_case,
    validate_debug_empty_price_df_chart_payload_contract_case,
    validate_chart_payload_optional_overlay_keys_contract_case,
    validate_gui_embedded_chart_contract_case,
    validate_gui_chart_workspace_contract_case,
    validate_gui_mouse_navigation_contract_case,
    validate_gui_dark_theme_and_keyboard_pan_contract_case,
    validate_gui_navigation_canvas_stub_cleanup_contract_case,
    validate_gui_navigation_canvas_stub_toolbar_contract_case,
    validate_record_signal_annotation_meta_contract_case,
    validate_workbench_theme_accent_symbol_contract_case,
    validate_gui_chart_recent_view_signal_overlay_contract_case,
    validate_gui_chart_overlay_layout_and_pan_contract_case,
    validate_gui_chart_margin_and_latest_extended_preview_contract_case,
    validate_gui_signal_annotation_and_forced_close_visual_contract_case,
    validate_gui_buy_signal_annotation_anchor_price_contract_case,
    validate_gui_trade_marker_and_tp_visual_contract_case,
    validate_gui_trade_count_and_sidebar_sync_contract_case,
    validate_gui_trade_box_capital_and_round_trip_contract_case,
    validate_gui_latest_raw_signal_preview_helper_contract_case,
    validate_gui_extended_preview_continuity_contract_case,
    validate_debug_entry_plan_marker_optional_contract_case,
    validate_gui_scanner_console_and_latest_contract_case,
    validate_gui_sidebar_latest_preview_contract_case,
    validate_gui_single_stock_refined_visual_contract_case,
    validate_gui_workbench_contract_case,
    validate_tool_module_path_normalization_case,
    validate_module_path_normalizer_accepts_path_objects_case,
    validate_module_loader_project_root_string_patch_case,
    validate_meta_quality_performance_memory_contract_case,
    validate_output_contract_case,
    validate_portfolio_sim_prepared_tool_contract_case,
    validate_quick_gate_bare_except_guard_contract_case,
    validate_quick_gate_output_path_guard_contract_case,
    validate_run_all_manifest_failure_master_summary_contract_case,
    validate_run_all_preflight_early_failure_dataset_contract_case,
    validate_scanner_prepared_tool_contract_case,
    validate_scanner_reference_clean_df_contract_case,
    validate_scanner_live_capital_contract_case,
    validate_dataset_prepare_fallback_write_traceability_case,
    validate_console_tail_read_error_traceability_case,
    validate_single_ticker_compounding_parity_contract_case,
)
from .synthetic_error_cases import (
    validate_downloader_main_error_path_case,
    validate_downloader_market_date_fallback_case,
    validate_downloader_sync_error_path_case,
    validate_downloader_universe_fetch_error_path_case,
    validate_downloader_universe_screening_init_error_path_case,
    validate_module_loader_error_path_case,
    validate_params_io_error_path_case,
    validate_preflight_error_path_case,
)
from .synthetic_data_quality_cases import (
    validate_load_clean_df_data_quality_case,
    validate_sanitize_ohlcv_expected_behavior_case,
    validate_sanitize_ohlcv_failfast_case,
)
from .synthetic_cli_cases import (
    validate_dataset_cli_contract_case,
    validate_breakout_quality_app_simple_report_contract_case,
    validate_extended_tool_cli_contract_case,
    validate_local_regression_cli_contract_case,
    validate_package_zip_commit_test_suite_orchestration_case,
    validate_package_zip_runtime_contract_case,
    validate_run_all_cli_error_usage_contract_case,
)
from .synthetic_strategy_cases import (
    validate_model_io_schema_case,
    validate_optimizer_interrupt_export_contract_case,
    validate_optimizer_objective_export_contract_case,
    validate_optimizer_session_milestone_cache_case,
    validate_optimizer_walk_forward_policy_contract_case,
    validate_ranking_scoring_sanity_case,
    validate_score_numerator_option_case,
    validate_strategy_minimum_viability_case,
    validate_strategy_repeatability_case,
    validate_strategy_reporting_schema_compatibility_case,
)
from .synthetic_regression_cases import (
    validate_optimizer_raw_cache_rerun_consistency_case,
    validate_optimizer_replay_raw_universe_contract_case,
    validate_run_all_repeatability_case,
    validate_scan_runner_repeatability_case,
    validate_scanner_worker_repeatability_case,
)
from .synthetic_flow_cases import (
    validate_synthetic_empty_backtest_df_contract_case,
    validate_synthetic_ensemble_reentry_consensus_watchlist_case,
    validate_synthetic_fill_below_limit_based_sizing_stop_still_enters_case,
    validate_synthetic_inherited_entry_fill_must_be_above_stop_case,
)


@dataclass(frozen=True)
class SyntheticValidatorEntry:
    validator: Callable
    layer: str
    cost_class: str
    impacted_modules: tuple[str, ...]

    @property
    def name(self) -> str:
        return self.validator.__name__


def _entry(validator, *, layer, cost_class, impacted_modules):
    return SyntheticValidatorEntry(
        validator=validator,
        layer=layer,
        cost_class=cost_class,
        impacted_modules=tuple(impacted_modules),
    )


def get_synthetic_validator_entries():
    return [
        _entry(validate_synthetic_same_day_buy_sell_forbidden_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/backtest_core.py", "core/portfolio_engine.py")),
        _entry(validate_synthetic_intraday_reprice_forbidden_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/trade_plans.py")),
        _entry(validate_synthetic_no_intraday_switch_after_failed_fill_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_missed_buy_no_replacement_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_exit_orders_only_for_held_positions_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/position_step.py")),
        _entry(validate_synthetic_fee_tax_net_equity_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/price_utils.py", "core/portfolio_stats.py")),
        _entry(validate_synthetic_missed_sell_accounting_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "tools/trade_analysis/trade_log.py")),
        _entry(validate_synthetic_round_trip_pnl_only_on_tail_exit_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_stats.py", "tools/trade_analysis/trade_log.py")),
        _entry(validate_synthetic_half_tp_full_year_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_stats.py", "tools/portfolio_sim/reporting.py")),
        _entry(validate_synthetic_same_bar_stop_priority_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/position_step.py", "core/backtest_core.py")),
        _entry(validate_synthetic_conservative_executable_exit_interpretation_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/position_step.py", "core/entry_plans.py")),
        _entry(validate_synthetic_extended_signal_a2_frozen_plan_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/extended_signals.py", "core/portfolio_candidates.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/backtest_core.py", "core/backtest_finalize.py", "tools/scanner/stock_processor.py", "tools/trade_analysis/entry_flow.py", "tools/trade_analysis/backtest.py")),
        _entry(validate_synthetic_empty_backtest_df_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/backtest_core.py", "core/backtest_finalize.py", "tools/validate/synthetic_flow_cases.py")),
        _entry(validate_synthetic_init_sl_single_source_runtime_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/entry_plans.py", "core/extended_signals.py", "core/position_step.py", "core/portfolio_exits.py", "core/price_utils.py", "tools/scanner/stock_processor.py", "tools/trade_analysis/entry_flow.py", "tools/trade_analysis/exit_flow.py", "tools/trade_analysis/backtest.py")),
        _entry(validate_synthetic_candidate_order_fill_layer_separation_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_portfolio_entry_preserves_fill_based_first_actionable_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_candidates.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/entry_plans.py")),
        _entry(validate_synthetic_fill_below_limit_based_sizing_stop_still_enters_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/entry_plans.py", "tools/trade_analysis/entry_flow.py")),
        _entry(validate_synthetic_inherited_entry_fill_must_be_above_stop_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/entry_plans.py", "core/extended_signals.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_ensemble_reentry_consensus_watchlist_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/portfolio_exits.py", "core/breakout_reentry.py", "tools/validate/synthetic_flow_cases.py")),
        _entry(validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_candidates.py", "core/extended_signals.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_extended_miss_buy_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/extended_signals.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_competing_candidates_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_candidates.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_same_day_sell_block_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_unexecutable_half_tp_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/position_step.py", "tools/trade_analysis/trade_log.py")),
        _entry(validate_synthetic_rotation_t_plus_one_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_proj_cost_cash_capped_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/buy_sort.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_history_ev_threshold_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_portfolio_history_filter_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_lookahead_prev_day_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_fast_data.py", "core/portfolio_engine.py")),
        _entry(validate_synthetic_setup_index_prev_day_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_fast_data.py", "core/extended_signals.py")),
        _entry(validate_synthetic_pit_same_day_exit_excluded_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_pit_multiple_same_day_exits_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_single_backtest_not_gated_by_own_history_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/backtest_core.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_single_backtest_uses_compounding_capital_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/capital_policy.py", "core/backtest_core.py", "core/backtest_finalize.py", "tools/trade_analysis/backtest.py")),
        _entry(validate_synthetic_param_guardrail_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/strategy_params.py", "config/execution_policy.py", "services/optimizer/objective_profiles.py")),
        _entry(validate_breakout_quality_policy_single_source_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_policy.py", "config/breakout_quality.py", "strategies/breakout/schema.py", "strategies/breakout/search_space.py", "filters/breakout_quality/contract.py", "filters/breakout_quality/features.py", "filters/breakout_quality/models/spec.py", "filters/breakout_quality/models/factory.py", "filters/breakout_quality/models/active.py", "filters/breakout_quality/models/legacy_compatibility.py", "filters/breakout_quality/models/runtime.py", "filters/breakout_quality/models/inception_time.py", "filters/breakout_quality/models/inception_time_market_set.py", "filters/breakout_quality/models/patch_transformer.py", "filters/breakout_quality/market_set.py", "filters/breakout_quality/dataset_store.py", "filters/breakout_quality/mantis_contract.py", "filters/breakout_quality/moment_contract.py",
            "filters/breakout_quality/models/mantis_v2.py", "filters/breakout_quality/models/moment.py", "filters/breakout_quality/models/modern_tcn.py", "filters/breakout_quality/models/multiscale_cnn.py", "filters/breakout_quality/models/ts2vec.py", "filters/breakout_quality/pretraining_store.py", "filters/breakout_quality/torch_runtime.py", "filters/breakout_quality/workflow_io.py", "services/breakout_quality/dataset_builder.py", "tools/filters/breakout_quality/build_dataset.py", "tools/filters/breakout_quality/build_pretraining_dataset.py", "tools/filters/breakout_quality/pretrain.py", "services/breakout_quality/train.py", "tools/filters/breakout_quality/train.py", "filters/breakout_quality/export_scores.py", "services/breakout_quality/evaluate.py", "tools/filters/breakout_quality/evaluate.py", "services/breakout_quality/report.py", "tools/filters/breakout_quality/report.py", "tools/audit/breakout_quality/regime.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_active_legacy_model_isolation_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("filters/breakout_quality/models/active.py", "filters/breakout_quality/models/factory.py", "filters/breakout_quality/models/legacy_compatibility.py", "filters/breakout_quality/models/runtime.py", "services/breakout_quality/train.py", "services/breakout_quality/train_continuous_ranker.py", "tools/validate/synthetic_breakout_quality_policy_cases.py")),
        _entry(validate_breakout_quality_chronological_embargo_case, layer="core_invariant", cost_class="fast", impacted_modules=("filters/breakout_quality/workflow_io.py", "filters/breakout_quality/features.py", "services/breakout_quality/train.py", "tools/filters/breakout_quality/train.py", "filters/breakout_quality/torch_runtime.py")),
        _entry(validate_breakout_quality_continuous_target_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("filters/breakout_quality/continuous_target.py", "services/breakout_quality/continuous_target_builder.py", "services/breakout_quality/continuous_target_metrics.py", "services/breakout_quality/continuous_target_preparation.py", "tools/filters/breakout_quality/prepare_continuous_target.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_continuous_ranker_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_target.py", "filters/breakout_quality/artifacts.py", "services/breakout_quality/train.py", "tools/filters/breakout_quality/train.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/filters/breakout_quality/train_continuous_ranker.py", "tools/filters/breakout_quality/pretrain.py", "filters/breakout_quality/export_scores.py", "services/breakout_quality/evaluate.py", "tools/filters/breakout_quality/evaluate.py", "services/breakout_quality/report.py", "tools/filters/breakout_quality/report.py", "tools/audit/breakout_quality/regime.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_all_event_no_time_ranker_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_target.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/filters/breakout_quality/train_continuous_ranker.py", "filters/breakout_quality/ranking_score_store.py", "config/strategy_compare.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_pairwise_ranker_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_ranker_quality.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/filters/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/continuous_ranker_pipeline.py", "tools/filters/breakout_quality/continuous_ranker_pipeline.py", "services/breakout_quality/continuous_ranker_comparison.py", "tools/filters/breakout_quality/compare_continuous_rankers.py", "filters/breakout_quality/ranking_score_store.py", "config/strategy_compare.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_daily_full_list_ndcg_pairwise_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/ranker_training_contract.py", "filters/breakout_quality/ranking_score_store.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/train_daily_ranker.py", "services/breakout_quality/ranker_cli.py", "tools/validate/synthetic_breakout_quality_model_cases.py")),
        _entry(validate_breakout_quality_full_horizon_target_components_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_target.py", "filters/breakout_quality/daily_ranker_data.py", "services/breakout_quality/daily_target_comparison.py", "services/breakout_quality/train_daily_ranker.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "tools/validate/synthetic_breakout_quality_model_cases.py")),
        _entry(validate_breakout_quality_reusable_model_component_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "config/strategy_compare.py", "core/params_io.py", "core/strategy_params.py", "filters/breakout_quality/continuous_target.py", "filters/breakout_quality/daily_ranker_data.py", "filters/breakout_quality/models/active.py", "filters/breakout_quality/models/inception_time.py", "filters/breakout_quality/models/spec.py", "filters/breakout_quality/ranker_training_contract.py", "filters/breakout_quality/risk_normalized_target.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/validate/synthetic_breakout_quality_model_cases.py")),
        _entry(validate_breakout_quality_low_adverse_target_component_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_target.py", "filters/breakout_quality/daily_ranker_data.py", "services/breakout_quality/train_daily_ranker.py", "tools/validate/synthetic_breakout_quality_model_cases.py")),
        _entry(validate_breakout_quality_multi_dl_ranker_architecture_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/train_daily_ranker.py", "services/breakout_quality/ranker_cli.py")),
        _entry(validate_breakout_quality_point_in_time_score_builder_contract_case, layer="core_invariant", cost_class="fast", impacted_modules=("config/breakout_quality.py", "filters/breakout_quality/continuous_target.py", "filters/breakout_quality/continuous_ranker_data.py", "filters/breakout_quality/daily_ranker_data.py", "filters/breakout_quality/paths.py", "services/breakout_quality/continuous_target_preparation.py", "tools/filters/breakout_quality/prepare_continuous_target.py", "services/breakout_quality/continuous_target_builder.py", "services/breakout_quality/continuous_target_metrics.py", "services/breakout_quality/continuous_ranker_pipeline.py", "tools/filters/breakout_quality/continuous_ranker_pipeline.py", "services/breakout_quality/point_in_time_scores.py", "services/breakout_quality/point_in_time_audit.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/filters/breakout_quality/train_continuous_ranker.py", "filters/breakout_quality/strategy_compare_engine.py", "filters/breakout_quality/strategy_compare_replay.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_selection_point_in_time_score_sort_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("config/strategy_compare.py", "filters/breakout_quality/continuous_ranker_data.py", "filters/breakout_quality/ranking_score_store.py", "filters/breakout_quality/runtime.py", "core/buy_sort.py", "core/portfolio_candidates.py", "core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "filters/breakout_quality/strategy_compare_engine.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_binary_dl_param_adaptation_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("strategies/breakout/search_space.py", "services/optimizer/outer_rolling_oos.py", "filters/breakout_quality/strategy_optimizer_policy.py", "filters/breakout_quality/strategy_param_training.py", "filters/breakout_quality/binary_pit_score_store.py", "services/breakout_quality/binary_point_in_time_scores.py", "filters/breakout_quality/strategy_compare_engine.py", "config/strategy_compare.py", "apps/research.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_trade_path_label_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/backtest_core.py", "core/backtest_finalize.py", "filters/breakout_quality/contract.py", "filters/breakout_quality/paths.py", "filters/breakout_quality/trade_path_label.py", "services/breakout_quality/trade_path_label_builder.py", "tools/filters/breakout_quality/build_trade_path_labels.py", "filters/breakout_quality/workflow_io.py", "services/breakout_quality/train.py", "tools/filters/breakout_quality/train.py", "filters/breakout_quality/export_scores.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py")),
        _entry(validate_breakout_quality_single_seed_single_entry_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("config/breakout_quality.py", "core/display_common.py", "core/training_progress.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "filters/breakout_quality/strategy_compare_engine.py", "filters/breakout_quality/strategy_multi_seed_robustness.py")),
        _entry(validate_strategy_compare_config_driven_app_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("apps/research.py", "config/research.py", "config/strategy_compare.py", "config/training_policy.py", "core/research_orchestration.py", "services/research/artifact_orchestrator.py", "core/buy_sort.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/strategy_comparison.py", "core/training_scheduler.py", "core/training_progress.py", "services/research/breakout_quality_application.py", "services/research/strategy_compare_training.py", "services/breakout_quality/train_continuous_ranker.py", "filters/breakout_quality/ranking_score_store.py", "filters/breakout_quality/runtime.py", "filters/breakout_quality/export_scores.py", "filters/breakout_quality/strategy_compare_engine.py", "filters/breakout_quality/strategy_compare_replay.py", "filters/breakout_quality/strategy_compare_execution.py", "filters/breakout_quality/strategy_compare_contracts.py", "filters/breakout_quality/strategy_compare_sources.py", "filters/breakout_quality/strategy_compare_reporting.py", "filters/breakout_quality/strategy_compare_diagnostics.py", "filters/breakout_quality/strategy_compare_preparation.py", "filters/breakout_quality/strategy_compare_preparation_status.py", "filters/breakout_quality/strategy_compare_dl_artifacts.py", "filters/breakout_quality/strategy_compare_runtime.py", "filters/breakout_quality/strategy_compare_reuse.py", "filters/breakout_quality/runtime_integration_gate.py", "filters/breakout_quality/strategy_comparison.py", "filters/breakout_quality/strategy_multi_seed_robustness.py", "filters/breakout_quality/strategy_optimizer_policy.py", "filters/breakout_quality/strategy_param_training.py", "services/optimizer/strategy_param_training.py", "services/optimizer/strategy_param_service.py", "services/optimizer/strategy_param_repository.py", "services/optimizer/outer_rolling_oos.py", "core/strategy_param_artifacts.py", "filters/breakout_quality/workflow_io.py", "services/breakout_quality/point_in_time_scores.py", "tools/validate/synthetic_breakout_quality_strategy_preparation_cases.py", "tools/validate/synthetic_breakout_quality_strategy_reuse_cases.py")),
        _entry(validate_strategy_compare_resolved_plan_transition_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("apps/research.py", "services/research/strategy_compare_application.py", "config/strategy_compare.py", "filters/breakout_quality/strategy_compare_plan.py", "filters/breakout_quality/strategy_compare_preparation.py", "filters/breakout_quality/strategy_compare_preparation_status.py", "filters/breakout_quality/strategy_compare_dl_artifacts.py", "filters/breakout_quality/strategy_compare_runtime.py", "filters/breakout_quality/strategy_compare_reuse.py", "filters/breakout_quality/strategy_comparison.py", "tools/validate/synthetic_breakout_quality_strategy_plan_cases.py")),
        _entry(validate_breakout_quality_daily_pit_strategy_runtime_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("config/strategy_compare.py", "core/portfolio_candidates.py", "filters/breakout_quality/continuous_ranker_data.py", "filters/breakout_quality/daily_ranker_data.py", "filters/breakout_quality/profile_ranker_data.py", "filters/breakout_quality/ranker_sample_contract.py", "filters/breakout_quality/ranking_score_store.py", "filters/breakout_quality/runtime.py", "filters/breakout_quality/strategy_compare_engine.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "services/breakout_quality/point_in_time_scores.py", "services/breakout_quality/continuous_ranker_pipeline.py", "tools/filters/breakout_quality/continuous_ranker_pipeline.py", "tools/filters/breakout_quality/rebuild_forward_oos_scores.py", "services/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/ranker_training.py", "tools/filters/breakout_quality/train_continuous_ranker.py", "services/breakout_quality/train_daily_ranker.py")),
        _entry(validate_breakout_quality_runtime_integration_gate_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("apps/research.py", "config/breakout_quality.py", "config/strategy_compare.py", "core/strategy_comparison.py", "filters/breakout_quality/artifacts.py", "filters/breakout_quality/contract.py", "filters/breakout_quality/export_scores.py", "filters/breakout_quality/runtime.py", "filters/breakout_quality/runtime_integration_gate.py", "filters/breakout_quality/score_store.py", "filters/breakout_quality/workflow_runtime_score_store.py", "filters/breakout_quality/strategy_comparison.py", "filters/breakout_quality/strategy_multi_seed_robustness.py", "services/breakout_quality/runtime_promotion.py", "tools/validate/synthetic_breakout_quality_strategy_app_cases.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_breakout_quality_audit_framework_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "config/audit.py", "services/audit/catalog.py", "tools/audit/catalog.py", "services/audit/runner.py", "tools/audit/runner.py")),
        _entry(validate_breakout_quality_runtime_artifact_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("filters/breakout_quality/artifacts.py", "filters/breakout_quality/mantis_contract.py", "filters/breakout_quality/moment_contract.py",
            "filters/breakout_quality/models/mantis_v2.py", "filters/breakout_quality/models/moment.py", "filters/breakout_quality/models/inception_time_market_set.py", "filters/breakout_quality/market_set.py", "filters/breakout_quality/dataset_store.py", "filters/breakout_quality/paths.py", "filters/breakout_quality/pretraining_store.py", "filters/breakout_quality/runtime.py", "filters/breakout_quality/score_store.py", "filters/breakout_quality/inference.py", "tools/filters/breakout_quality/pretrain.py", "services/breakout_quality/train.py", "tools/filters/breakout_quality/train.py", "filters/breakout_quality/export_scores.py", "services/breakout_quality/evaluate.py", "tools/filters/breakout_quality/evaluate.py", "services/breakout_quality/report.py", "tools/filters/breakout_quality/report.py", "tools/audit/breakout_quality/regime.py", "core/signal_utils.py")),
        _entry(validate_breakout_quality_strategy_comparison_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "filters/breakout_quality/strategy_compare_engine.py", "filters/breakout_quality/strategy_compare_contracts.py", "core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "services/portfolio_replay.py")),
        _entry(validate_breakout_quality_strategy_readable_report_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("core/display_common.py", "core/training_progress.py", "services/research/breakout_quality_application.py", "services/research/strategy_compare_training.py", "filters/breakout_quality/strategy_compare_engine.py", "filters/breakout_quality/strategy_compare_replay.py", "filters/breakout_quality/strategy_compare_execution.py", "filters/breakout_quality/strategy_compare_contracts.py", "filters/breakout_quality/strategy_compare_sources.py", "filters/breakout_quality/strategy_compare_reporting.py", "filters/breakout_quality/strategy_compare_diagnostics.py", "filters/breakout_quality/strategy_comparison.py", "filters/breakout_quality/strategy_multi_seed_robustness.py", "filters/breakout_quality/strategy_param_training.py", "services/optimizer/strategy_param_training.py", "services/breakout_quality/point_in_time_audit.py", "services/breakout_quality/report.py", "tools/filters/breakout_quality/report.py", "core/strategy_dashboard.py", "services/optimizer/callbacks.py", "services/optimizer/outer_rolling_oos.py", "core/console_report.py", "core/report_metrics.py", "core/report_style.py")),
        _entry(validate_breakout_quality_legacy_research_cleanup_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("filters/breakout_quality/strategy_comparison.py", "filters/breakout_quality/strategy_param_training.py", "services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "services/breakout_quality/trade_path_label_builder.py", "tools/filters/breakout_quality/build_trade_path_labels.py", "tools/filters/breakout_quality/build_pretraining_dataset.py", "tools/filters/breakout_quality/pretrain.py", "doc/CMD.md", "doc/ARCHITECTURE.md", "doc/TEST_SUITE_CHECKLIST.md")),
        _entry(validate_price_utils_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/price_utils.py",)),
        _entry(validate_signal_utils_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/signal_utils.py", "core/strategy_params.py")),
        _entry(validate_history_filters_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/history_filters.py",)),
        _entry(validate_portfolio_stats_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/portfolio_stats.py",)),
        _entry(validate_exact_accounting_ledger_conservation_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/price_utils.py")),
        _entry(validate_exact_accounting_cost_basis_allocation_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/entry_plans.py", "core/position_step.py")),
        _entry(validate_exact_accounting_tick_limit_integer_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/price_utils.py")),
        _entry(validate_exact_accounting_cash_risk_boundary_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/entry_plans.py", "core/price_utils.py")),
        _entry(validate_exact_accounting_single_vs_portfolio_parity_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/backtest_core.py", "core/backtest_finalize.py", "core/portfolio_exits.py", "core/exact_accounting.py")),
        _entry(validate_exact_accounting_display_derived_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/entry_plans.py", "core/position_step.py")),
        _entry(validate_exact_accounting_display_leg_reconciliation_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/exact_accounting.py", "core/portfolio_exits.py", "tools/trade_analysis/exit_flow.py")),
        _entry(validate_independent_oracle_golden_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/price_utils.py", "core/history_filters.py", "core/portfolio_stats.py")),
        _entry(validate_registry_checklist_entry_consistency_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/validate/synthetic_cases.py")),
        _entry(validate_checklist_t_formal_command_single_entry_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_checklist_done_test_summary_markdown_structure_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_checklist_t_single_entry_delimiter_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_transition_format_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_ordering_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_new_transition_first_occurrence_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_transition_sequence_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_checklist_summary_tables_sorted_by_id_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_cases_import_target_resolution_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_cases.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_quick_gate_synthetic_registry_import_targets_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_quick_gate.py", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_single_backtest_stats_legacy_schema_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/backtest_finalize.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_debug_backtest_entry_cash_path_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/backtest.py", "tools/trade_analysis/entry_flow.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_price_utils_array_tick_normalization_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/price_utils.py", "core/signal_utils.py", "core/backtest_core.py", "core/portfolio_fast_data.py", "core/portfolio_candidates.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "core/position_step.py", "core/portfolio_exits.py", "tools/scanner/stock_processor.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_test_suite_help_text_mentions_stable_theme_tokens_case, layer="meta_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/validate/synthetic_cases.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_portfolio_rotation_mark_to_market_return_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_portfolio_core_module_boundary_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "tools/local_regression/meta_quality_targets.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_registry_metadata_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_cases.py", "tools/validate/synthetic_breakout_quality_support.py", "tools/validate/synthetic_breakout_quality_policy_cases.py", "tools/validate/synthetic_breakout_quality_artifact_cases.py", "tools/validate/synthetic_breakout_quality_model_cases.py", "tools/validate/synthetic_breakout_quality_audit_cases.py", "tools/validate/synthetic_breakout_quality_pit_cases.py", "tools/validate/synthetic_breakout_quality_strategy_cases.py", "tools/validate/synthetic_breakout_quality_strategy_app_cases.py", "tools/validate/synthetic_breakout_quality_strategy_plan_cases.py", "tools/validate/synthetic_breakout_quality_strategy_preparation_cases.py", "tools/validate/synthetic_breakout_quality_strategy_reuse_cases.py")),
        _entry(validate_core_trading_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_critical_helper_single_source_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/price_utils.py", "core/capital_policy.py", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_policy_contract_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/meta_quality_targets.py", "tools/validate/synthetic_meta_cases.py", "core/capital_policy.py", "core/strategy_params.py", "core/params_io.py", "config/execution_policy.py", "config/training_policy.py")),
        _entry(validate_test_suite_orchestrator_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_formal_step_entry_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/formal_pipeline.py", "tools/local_regression/meta_quality_targets.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_formal_step_implementation_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/meta_quality_targets.py", "tools/validate/main.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_critical_file_coverage_minimum_gate_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_meta_quality_coverage_threshold_uses_target_scope_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/meta_quality_coverage.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/manifest.json", "tools/local_regression/common.py")),
        _entry(validate_critical_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/manifest.json", "tools/local_regression/common.py")),
        _entry(validate_entry_path_critical_coverage_gate_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_peak_traced_memory_tracker_context_management_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_chain_checks.py", "tools/local_regression/run_meta_quality.py", "tools/local_regression/run_ml_smoke.py", "tools/local_regression/run_quick_gate.py", "tools/validate/main.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_known_bad_fault_injection_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_meta_cases.py",)),
        _entry(validate_cmd_document_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md",)),
        _entry(validate_gui_workbench_documentation_sync_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md", "doc/ARCHITECTURE.md", "tools/workbench_ui/single_stock_inspector.py")),
        _entry(validate_architecture_workbench_entry_file_tree_sync_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/ARCHITECTURE.md", "apps/workbench.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_model_param_source_resolution_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/ARCHITECTURE.md", "core/model_paths.py", "tools/local_regression/run_all.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_architecture_local_regression_meta_quality_file_tree_sync_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/ARCHITECTURE.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_trade_analysis_legacy_naming_documentation_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md", "doc/ARCHITECTURE.md", "tools/trade_analysis/trade_log.py")),
        _entry(validate_trade_analysis_canonical_alias_export_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/__init__.py", "tools/trade_analysis/trade_log.py", "doc/CMD.md", "doc/ARCHITECTURE.md")),
        _entry(validate_validate_runtime_tmp_output_staging_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_error_cases.py", "tools/validate/synthetic_regression_cases.py", "tools/local_regression/run_all.py", "doc/CMD.md", "doc/ARCHITECTURE.md")),
        _entry(validate_no_legacy_app_entry_doc_references_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md", "doc/ARCHITECTURE.md", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_app_thin_wrapper_export_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("apps/portfolio_sim.py", "apps/vip_scanner.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_no_reverse_app_layer_dependencies_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/ARCHITECTURE.md", "tools/validate/meta_contracts.py")),
        _entry(validate_no_top_level_import_cycles_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_single_formal_test_entry_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/formal_pipeline.py")),
        _entry(validate_checklist_physical_trading_principles_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_specific_pass_only_exception_traceability_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/runtime_utils.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_broad_exception_traceability_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/workbench_ui/single_stock_inspector.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_gui_tcl_fallback_traceability_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/workbench.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_optional_dependency_fallback_traceability_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/downloader/runtime.py", "tools/workbench_ui/single_stock_inspector.py", "tools/validate/main.py")),
        _entry(validate_display_reporting_sanity_case, layer="output_contract", cost_class="fast", impacted_modules=("core/display.py", "core/strategy_dashboard.py", "services/optimizer/callbacks.py", "tools/optimizer/callbacks.py", "services/optimizer/static_ensemble_dashboard.py", "tools/optimizer/static_ensemble_dashboard.py", "tools/portfolio_sim/main.py", "tools/scanner/reporting.py", "tools/workbench_ui/portfolio_backtest_inspector.py")),
        _entry(validate_validate_console_summary_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py",)),
        _entry(validate_portfolio_yearly_report_schema_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/reporting.py",)),
        _entry(validate_test_suite_summary_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_manifest_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_all.py")),
        _entry(validate_test_suite_summary_optional_dataset_skip_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_checklist_status_sync_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "doc/TEST_SUITE_CHECKLIST.md")),
        _entry(validate_test_suite_summary_meta_quality_guardrail_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_test_suite_summary_meta_quality_memory_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_test_suite_summary_preflight_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_dataset_prepare_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_all.py")),
        _entry(validate_test_suite_summary_unreadable_payload_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_issue_excel_report_schema_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py",)),
        _entry(validate_portfolio_export_report_artifacts_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/reporting.py",)),
        _entry(validate_output_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/validate/reporting.py")),
        _entry(validate_dataset_fingerprint_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/local_regression/run_all.py")),
        _entry(validate_reduced_dataset_dynamic_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_run_all_dataset_prepare_pass_main_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_atomic_write_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_atomic_write_retry_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_atomic_write_cleanup_error_preserves_root_exception_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_validate_summary_atomic_write_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py", "tools/local_regression/common.py")),
        _entry(validate_portfolio_sim_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/main.py",)),
        _entry(validate_scanner_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/scanner/scan_runner.py",)),
        _entry(validate_scanner_reference_clean_df_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/real_case_io.py", "tools/scanner/stock_processor.py")),
        _entry(validate_scanner_live_capital_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("core/capital_policy.py", "config/execution_policy.py", "core/price_utils.py", "tools/scanner/stock_processor.py")),
        _entry(validate_debug_trade_log_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/trade_log.py",)),
        _entry(validate_debug_trade_log_chart_context_optional_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/trade_analysis/trade_log.py")),
        _entry(validate_debug_chart_payload_without_html_export_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/backtest.py", "tools/trade_analysis/reporting.py", "tools/trade_analysis/trade_log.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_debug_empty_price_df_chart_payload_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/reporting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_chart_payload_optional_overlay_keys_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_workbench_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/workbench.py", "tools/workbench_ui/main.py", "tools/workbench_ui/workbench.py", "tools/workbench_ui/single_stock_inspector.py", "tools/workbench_ui/portfolio_backtest_inspector.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/trade_log.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_embedded_chart_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/workbench_ui/single_stock_inspector.py", "tools/workbench_ui/workbench.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_chart_workspace_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/workbench_ui/workbench.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_mouse_navigation_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_dark_theme_and_keyboard_pan_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/workbench.py", "tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_navigation_canvas_stub_cleanup_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_contract_cases.py",)),
        _entry(validate_gui_navigation_canvas_stub_toolbar_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_contract_cases.py",)),
        _entry(validate_record_signal_annotation_meta_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_chart_recent_view_signal_overlay_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/trade_analysis/entry_flow.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_workbench_theme_accent_symbol_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/workbench.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_scanner_console_and_latest_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/scanner/scan_runner.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_sidebar_latest_preview_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_single_stock_refined_visual_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/workbench_ui/workbench.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/entry_flow.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_extended_preview_continuity_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/entry_flow.py", "tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_chart_margin_and_latest_extended_preview_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_signal_annotation_and_forced_close_visual_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_buy_signal_annotation_anchor_price_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_trade_marker_and_tp_visual_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/trade_analysis/exit_flow.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_trade_count_and_sidebar_sync_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/single_stock_inspector.py", "tools/workbench_ui/portfolio_backtest_inspector.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/backtest.py", "tools/trade_analysis/exit_flow.py", "core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "core/portfolio_entries.py", "core/portfolio_entry_plans.py", "core/portfolio_entry_selection.py", "core/portfolio_entry_selection_common.py", "core/portfolio_entry_selection_max_dl.py", "tools/portfolio_sim/reporting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_trade_box_capital_and_round_trip_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/trade_log.py", "tools/trade_analysis/backtest.py", "tools/trade_analysis/charting.py", "tools/trade_analysis/exit_flow.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_latest_raw_signal_preview_helper_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/backtest.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_chart_overlay_layout_and_pan_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/workbench_ui/workbench.py", "tools/workbench_ui/single_stock_inspector.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_debug_entry_plan_marker_optional_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/trade_analysis/entry_flow.py", "tools/trade_analysis/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_tool_module_path_normalization_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/external_tool_checks.py")),
        _entry(validate_module_path_normalizer_accepts_path_objects_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_module_loader_project_root_string_patch_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/synthetic_contract_cases.py", "tools/validate/synthetic_error_cases.py")),
        _entry(validate_local_regression_summary_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py", "tools/validate/reporting.py")),
        _entry(validate_meta_quality_performance_memory_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_meta_quality_reuses_existing_coverage_artifacts_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py", "tools/validate/main.py")),
        _entry(validate_run_all_preflight_early_failure_dataset_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_run_all_manifest_failure_master_summary_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_artifact_lifecycle_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/local_regression/run_all.py")),
        _entry(validate_quick_gate_bare_except_guard_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_quick_gate.py",)),
        _entry(validate_quick_gate_output_path_guard_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_quick_gate.py", "core/output_paths.py", "core/log_utils.py", "services/portfolio_replay_runtime.py")),
        _entry(validate_dataset_prepare_fallback_write_traceability_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_console_tail_read_error_traceability_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_single_ticker_compounding_parity_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("core/capital_policy.py", "core/backtest_core.py", "core/portfolio_engine.py", "core/portfolio_benchmark.py", "core/portfolio_candidates.py", "core/portfolio_replay_support.py", "core/portfolio_levels.py", "core/portfolio_ensemble.py", "tools/validate/real_case_runners.py")),
        _entry(validate_params_io_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("core/params_io.py",)),
        _entry(validate_module_loader_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/validate/module_loader.py",)),
        _entry(validate_preflight_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/validate/preflight_env.py",)),
        _entry(validate_downloader_market_date_fallback_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_universe_fetch_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_universe_screening_init_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_sync_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/sync.py",)),
        _entry(validate_downloader_main_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/main.py",)),
        _entry(validate_sanitize_ohlcv_expected_behavior_case, layer="data_quality", cost_class="fast", impacted_modules=("core/data_utils.py",)),
        _entry(validate_sanitize_ohlcv_failfast_case, layer="data_quality", cost_class="fast", impacted_modules=("core/data_utils.py",)),
        _entry(validate_load_clean_df_data_quality_case, layer="data_quality", cost_class="fast", impacted_modules=("tools/validate/real_case_io.py", "core/data_utils.py")),
        _entry(validate_breakout_quality_app_simple_report_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "core/console_report.py")),
        _entry(validate_dataset_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("services/research/breakout_quality_application.py", "tools/filters/breakout_quality/application.py", "config/breakout_quality.py", "services/breakout_quality/rolling_timing.py", "core/display_common.py", "core/console_report.py", "filters/breakout_quality/mantis_contract.py", "filters/breakout_quality/moment_contract.py",
            "filters/breakout_quality/models/mantis_v2.py", "filters/breakout_quality/models/moment.py", "services/breakout_quality/dataset_builder.py", "tools/filters/breakout_quality/build_dataset.py", "tools/filters/breakout_quality/pretrain.py", "services/breakout_quality/continuous_target_preparation.py", "tools/filters/breakout_quality/prepare_continuous_target.py", "tools/validate/cli.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_local_regression_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py", "tools/local_regression/run_quick_gate.py")),
        _entry(validate_package_zip_runtime_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/package_zip.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_package_zip_commit_test_suite_orchestration_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/run_bundle.py", "apps/package_zip.py", "apps/test_suite.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_run_all_cli_error_usage_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_extended_tool_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "services/optimizer/application.py", "tools/optimizer/main.py", "tools/scanner/scan_runner.py")),
        _entry(validate_model_io_schema_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/optimizer/study_utils.py", "tools/optimizer/study_utils.py", "tools/scanner/stock_processor.py")),
        _entry(validate_optimizer_interrupt_export_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/optimizer/application.py", "tools/optimizer/main.py", "services/optimizer/runtime.py", "tools/optimizer/runtime.py")),
        _entry(validate_optimizer_objective_export_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/optimizer/objective_runner.py", "services/optimizer/runtime.py", "tools/optimizer/runtime.py", "services/optimizer/study_utils.py", "tools/optimizer/study_utils.py", "services/optimizer/robustness.py", "tools/optimizer/robustness.py", "config/training_policy.py")),
        _entry(validate_optimizer_session_milestone_cache_case, layer="strategy_contract", cost_class="fast", impacted_modules=("services/optimizer/session.py", "tools/optimizer/session.py", "services/optimizer/callbacks.py", "tools/optimizer/callbacks.py", "services/optimizer/objective_runner.py")),
        _entry(validate_optimizer_walk_forward_policy_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/walk_forward_policy.py", "config/training_policy.py", "services/optimizer/callbacks.py", "tools/optimizer/callbacks.py", "services/optimizer/static_ensemble_dashboard.py", "tools/optimizer/static_ensemble_dashboard.py", "services/optimizer/score_display.py", "tools/optimizer/score_display.py", "services/optimizer/application.py", "tools/optimizer/main.py", "services/optimizer/robustness.py", "tools/optimizer/robustness.py", "services/optimizer/outer_rolling_oos.py", "services/optimizer/walk_forward.py", "tools/optimizer/walk_forward.py")),
        _entry(validate_ranking_scoring_sanity_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/buy_sort.py", "core/portfolio_stats.py")),
        _entry(validate_score_numerator_option_case, layer="strategy_contract", cost_class="fast", impacted_modules=("config/training_policy.py", "core/portfolio_stats.py", "core/strategy_dashboard.py", "core/scanner_display.py")),
        _entry(validate_use_compounding_failfast_guardrail_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/strategy_params.py", "core/params_io.py", "config/execution_policy.py")),
        _entry(validate_strategy_repeatability_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "services/optimizer/objective_runner.py", "tools/scanner/stock_processor.py")),
        _entry(validate_strategy_minimum_viability_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "core/strategy_dashboard.py", "tools/scanner/reporting.py", "tools/portfolio_sim/reporting.py")),
        _entry(validate_strategy_reporting_schema_compatibility_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "services/optimizer/runtime.py", "tools/optimizer/runtime.py", "tools/portfolio_sim/reporting.py", "tools/scanner/stock_processor.py")),
        _entry(validate_scanner_worker_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/scanner/stock_processor.py",)),
        _entry(validate_scan_runner_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/scanner/scan_runner.py",)),
        _entry(validate_optimizer_raw_cache_rerun_consistency_case, layer="regression_contract", cost_class="medium", impacted_modules=("services/optimizer/raw_cache.py", "tools/optimizer/raw_cache.py",)),
        _entry(validate_optimizer_replay_raw_universe_contract_case, layer="regression_contract", cost_class="medium", impacted_modules=("core/raw_universe_contract.py", "core/active_param_ensemble.py", "services/portfolio_replay.py", "services/optimizer/raw_cache.py", "services/optimizer/application.py", "tools/optimizer/main.py", "services/optimizer/outer_rolling_oos.py")),
        _entry(validate_run_all_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/local_regression/run_all.py",)),
    ]


def get_synthetic_validator_metadata():
    return [
        {
            "name": entry.name,
            "layer": entry.layer,
            "cost_class": entry.cost_class,
            "impacted_modules": list(entry.impacted_modules),
        }
        for entry in get_synthetic_validator_entries()
    ]


def get_synthetic_validators():
    return [entry.validator for entry in get_synthetic_validator_entries()]


def run_synthetic_consistency_suite(base_params):
    all_results = []
    summaries = []
    validator_entries = get_synthetic_validator_entries()

    for entry in validator_entries:
        results, summary = entry.validator(base_params)
        all_results.extend(results)
        summaries.append(summary)

    return all_results, summaries
