from dataclasses import dataclass
from typing import Callable

from .synthetic_param_cases import (
    validate_synthetic_history_ev_threshold_case,
    validate_synthetic_lookahead_prev_day_only_case,
    validate_synthetic_param_guardrail_case,
    validate_synthetic_pit_multiple_same_day_exits_case,
    validate_synthetic_pit_same_day_exit_excluded_case,
    validate_synthetic_portfolio_history_filter_only_case,
    validate_synthetic_proj_cost_cash_capped_case,
    validate_synthetic_single_backtest_uses_compounding_capital_case,
    validate_synthetic_single_backtest_not_gated_by_own_history_case,
    validate_use_compounding_failfast_guardrail_case,
)
from .synthetic_history_cases import (
    validate_synthetic_setup_index_prev_day_only_case,
)
from .synthetic_portfolio_cases import (
    validate_synthetic_candidate_order_fill_layer_separation_case,
    validate_synthetic_portfolio_entry_preserves_fill_based_first_actionable_case,
    validate_synthetic_competing_candidates_case,
    validate_synthetic_conservative_executable_exit_interpretation_case,
    validate_synthetic_exit_orders_only_for_held_positions_case,
    validate_synthetic_extended_miss_buy_case,
    validate_synthetic_extended_signal_a2_frozen_plan_case,
    validate_synthetic_init_sl_single_source_runtime_case,
    validate_synthetic_fee_tax_net_equity_case,
    validate_synthetic_half_tp_full_year_case,
    validate_synthetic_intraday_reprice_forbidden_case,
    validate_synthetic_missed_buy_no_replacement_case,
    validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case,
    validate_synthetic_missed_sell_accounting_case,
    validate_synthetic_no_intraday_switch_after_failed_fill_case,
    validate_synthetic_rotation_t_plus_one_case,
    validate_synthetic_round_trip_pnl_only_on_tail_exit_case,
    validate_synthetic_same_bar_stop_priority_case,
    validate_synthetic_same_day_buy_sell_forbidden_case,
    validate_synthetic_same_day_sell_block_case,
    validate_synthetic_unexecutable_half_tp_case,
)
from .synthetic_unit_cases import (
    validate_exact_accounting_cash_risk_boundary_case,
    validate_exact_accounting_cost_basis_allocation_case,
    validate_exact_accounting_display_derived_case,
    validate_exact_accounting_display_leg_reconciliation_case,
    validate_exact_accounting_ledger_conservation_case,
    validate_exact_accounting_single_vs_portfolio_parity_case,
    validate_exact_accounting_tick_limit_integer_case,
    validate_history_filters_unit_case,
    validate_independent_oracle_golden_case,
    validate_portfolio_stats_unit_case,
    validate_price_utils_unit_case,
    validate_signal_utils_unit_case,
)
from .synthetic_meta_cases import (
    validate_checklist_t_formal_command_single_entry_case,
    validate_checklist_done_test_summary_markdown_structure_case,
    validate_checklist_t_single_entry_delimiter_case,
    validate_checklist_g_transition_format_case,
    validate_checklist_g_ordering_case,
    validate_checklist_g_new_transition_first_occurrence_case,
    validate_checklist_g_transition_sequence_case,
    validate_checklist_summary_tables_sorted_by_id_case,
    validate_synthetic_cases_import_target_resolution_contract_case,
    validate_quick_gate_synthetic_registry_import_targets_contract_case,
    validate_price_utils_array_tick_normalization_contract_case,
    validate_test_suite_help_text_mentions_stable_theme_tokens_case,
    validate_portfolio_rotation_mark_to_market_return_contract_case,
    validate_portfolio_core_module_boundary_contract_case,
    validate_debug_backtest_entry_cash_path_contract_case,
    validate_single_backtest_stats_legacy_schema_contract_case,
    validate_cmd_document_contract_case,
    validate_core_trading_modules_in_coverage_targets_case,
    validate_critical_helper_single_source_contract_case,
    validate_policy_contract_modules_in_coverage_targets_case,
    validate_meta_quality_coverage_threshold_uses_target_scope_case,
    validate_coverage_threshold_floor_case,
    validate_critical_coverage_threshold_floor_case,
    validate_critical_file_coverage_minimum_gate_case,
    validate_entry_path_critical_coverage_gate_case,
    validate_formal_step_entry_coverage_targets_case,
    validate_formal_step_implementation_coverage_targets_case,
    validate_known_bad_fault_injection_case,
    validate_no_legacy_app_entry_doc_references_case,
    validate_app_thin_wrapper_export_contract_case,
    validate_no_reverse_app_layer_dependencies_case,
    validate_no_top_level_import_cycles_case,
    validate_peak_traced_memory_tracker_context_management_case,
    validate_checklist_physical_trading_principles_contract_case,
    validate_specific_pass_only_exception_traceability_contract_case,
    validate_broad_exception_traceability_contract_case,
    validate_gui_tcl_fallback_traceability_contract_case,
    validate_gui_workbench_documentation_sync_case,
    validate_architecture_workbench_entry_file_tree_sync_case,
    validate_model_param_source_resolution_contract_case,
    validate_architecture_local_regression_meta_quality_file_tree_sync_case,
    validate_trade_analysis_legacy_naming_documentation_contract_case,
    validate_trade_analysis_canonical_alias_export_contract_case,
    validate_validate_runtime_tmp_output_staging_contract_case,
    validate_optional_dependency_fallback_traceability_contract_case,
    validate_registry_checklist_entry_consistency_case,
    validate_research_report_contract_freeze_case,
    validate_single_formal_test_entry_contract_case,
    validate_synthetic_registry_metadata_contract_case,
    validate_test_suite_orchestrator_coverage_targets_case,
)
from .synthetic_breakout_quality_policy_cases import (
    validate_breakout_quality_policy_single_source_case,
    validate_breakout_quality_active_legacy_model_isolation_contract_case,
    validate_breakout_quality_chronological_embargo_case,
)
from .synthetic_breakout_quality_artifact_cases import (
    validate_breakout_quality_runtime_artifact_contract_case,
)
from .synthetic_breakout_quality_model_cases import (
    validate_breakout_quality_continuous_target_contract_case,
    validate_breakout_quality_continuous_ranker_contract_case,
    validate_breakout_quality_all_event_no_time_ranker_contract_case,
    validate_breakout_quality_pairwise_ranker_contract_case,
    validate_breakout_quality_daily_full_list_ndcg_pairwise_contract_case,
    validate_breakout_quality_full_horizon_target_components_contract_case,
    validate_breakout_quality_reusable_model_component_contract_case,
    validate_breakout_quality_low_adverse_target_component_contract_case,
    validate_breakout_quality_conditional_mfe_safety_single_model_contract_case,
    validate_breakout_quality_reverse_conditional_mfe_ab_contract_case,
    validate_breakout_quality_safety_raw_mfe_duo_contract_case,
    validate_breakout_quality_safety_raw_mfe_hmhs_tri_head_contract_case,
    validate_breakout_quality_hmhs_single_head_contract_case,
    validate_breakout_quality_nonlinear_hmhs_head_contract_case,
    validate_breakout_quality_joint_min_target_contract_case,
    validate_breakout_quality_joint_attention_pool_contract_case,
    validate_breakout_quality_modern_tcn_joint_min_contract_case,
    validate_breakout_quality_patch_transformer_joint_min_contract_case,
    validate_breakout_quality_mr13aa_patch_transformer_h_target_contract_case,
    validate_breakout_quality_mr13ab_first_breach_pure_mfe_contract_case,
    validate_breakout_quality_mr13ac_predicted_upside_conditional_safety_contract_case,
    validate_breakout_quality_mr13ad_predicted_safety_conditional_mfe_contract_case,
    validate_breakout_quality_mr13ae_predicted_safety_context_pure_mfe_contract_case,
    validate_breakout_quality_mr13af_high_safety_weighted_pure_mfe_contract_case,
    validate_breakout_quality_mr13ag_mfe_winner_safety_weighted_pure_mfe_contract_case,
    validate_breakout_quality_multi_dl_ranker_architecture_contract_case,
)
from .synthetic_breakout_quality_audit_cases import (
    validate_breakout_quality_audit_framework_contract_case,
)
from .synthetic_breakout_quality_pit_cases import (
    validate_breakout_quality_point_in_time_score_builder_contract_case,
    validate_breakout_quality_pit_training_performance_semantics_case,
    validate_breakout_quality_selection_point_in_time_score_sort_contract_case,
)
from .synthetic_breakout_quality_strategy_cases import (
    validate_breakout_quality_strategy_comparison_contract_case,
    validate_breakout_quality_binary_dl_param_adaptation_contract_case,
    validate_breakout_quality_trade_path_label_contract_case,
    validate_breakout_quality_legacy_research_cleanup_contract_case,
    validate_breakout_quality_strategy_readable_report_contract_case,
)
from .synthetic_breakout_quality_strategy_app_cases import (
    validate_breakout_quality_single_seed_single_entry_contract_case,
    validate_strategy_compare_config_driven_app_contract_case,
    validate_mr13z_c75_conversion_contract_case,
    validate_breakout_quality_daily_pit_strategy_runtime_contract_case,
    validate_breakout_quality_runtime_integration_gate_contract_case,
)
from .synthetic_breakout_quality_strategy_plan_cases import (
    validate_strategy_compare_resolved_plan_transition_contract_case,
)
from .synthetic_display_cases import validate_display_reporting_sanity_case
from .synthetic_reporting_cases import (
    validate_issue_excel_report_schema_case,
    validate_portfolio_export_report_artifacts_case,
    validate_portfolio_yearly_report_schema_case,
    validate_test_suite_summary_checklist_status_sync_case,
    validate_test_suite_summary_dataset_prepare_failure_reporting_case,
    validate_test_suite_summary_failure_reporting_case,
    validate_test_suite_summary_manifest_failure_reporting_case,
    validate_test_suite_summary_meta_quality_guardrail_reporting_case,
    validate_test_suite_summary_meta_quality_memory_reporting_case,
    validate_test_suite_summary_optional_dataset_skip_case,
    validate_test_suite_summary_preflight_failure_reporting_case,
    validate_test_suite_summary_reporting_case,
    validate_test_suite_summary_unreadable_payload_reporting_case,
    validate_validate_console_summary_reporting_case,
)
from .synthetic_contract_cases import (
    validate_artifact_lifecycle_contract_case,
    validate_atomic_write_contract_case,
    validate_atomic_write_retry_contract_case,
    validate_atomic_write_cleanup_error_preserves_root_exception_case,
    validate_validate_summary_atomic_write_contract_case,
    validate_dataset_fingerprint_contract_case,
    validate_reduced_dataset_dynamic_contract_case,
    validate_run_all_dataset_prepare_pass_main_contract_case,
    validate_local_regression_summary_contract_case,
    validate_meta_quality_reuses_existing_coverage_artifacts_case,
    validate_debug_trade_log_chart_context_optional_case,
    validate_debug_trade_log_prepared_tool_contract_case,
    validate_debug_chart_payload_without_html_export_contract_case,
    validate_debug_empty_price_df_chart_payload_contract_case,
    validate_chart_payload_optional_overlay_keys_contract_case,
    validate_gui_embedded_chart_contract_case,
    validate_gui_chart_workspace_contract_case,
    validate_gui_mouse_navigation_contract_case,
    validate_gui_dark_theme_and_keyboard_pan_contract_case,
    validate_gui_navigation_canvas_stub_cleanup_contract_case,
    validate_gui_navigation_canvas_stub_toolbar_contract_case,
    validate_record_signal_annotation_meta_contract_case,
    validate_workbench_theme_accent_symbol_contract_case,
    validate_gui_chart_recent_view_signal_overlay_contract_case,
    validate_gui_chart_overlay_layout_and_pan_contract_case,
    validate_gui_chart_margin_and_latest_extended_preview_contract_case,
    validate_gui_signal_annotation_and_forced_close_visual_contract_case,
    validate_gui_buy_signal_annotation_anchor_price_contract_case,
    validate_gui_trade_marker_and_tp_visual_contract_case,
    validate_gui_trade_count_and_sidebar_sync_contract_case,
    validate_gui_trade_box_capital_and_round_trip_contract_case,
    validate_gui_latest_raw_signal_preview_helper_contract_case,
    validate_gui_extended_preview_continuity_contract_case,
    validate_debug_entry_plan_marker_optional_contract_case,
    validate_gui_scanner_console_and_latest_contract_case,
    validate_gui_sidebar_latest_preview_contract_case,
    validate_gui_single_stock_refined_visual_contract_case,
    validate_gui_workbench_contract_case,
    validate_tool_module_path_normalization_case,
    validate_module_path_normalizer_accepts_path_objects_case,
    validate_module_loader_project_root_string_patch_case,
    validate_meta_quality_performance_memory_contract_case,
    validate_output_contract_case,
    validate_portfolio_sim_prepared_tool_contract_case,
    validate_quick_gate_bare_except_guard_contract_case,
    validate_quick_gate_output_path_guard_contract_case,
    validate_run_all_manifest_failure_master_summary_contract_case,
    validate_run_all_preflight_early_failure_dataset_contract_case,
    validate_scanner_prepared_tool_contract_case,
    validate_scanner_reference_clean_df_contract_case,
    validate_scanner_live_capital_contract_case,
    validate_dataset_prepare_fallback_write_traceability_case,
    validate_console_tail_read_error_traceability_case,
    validate_single_ticker_compounding_parity_contract_case,
)
from .synthetic_error_cases import (
    validate_downloader_main_error_path_case,
    validate_downloader_market_date_fallback_case,
    validate_downloader_sync_error_path_case,
    validate_downloader_universe_fetch_error_path_case,
    validate_downloader_universe_screening_init_error_path_case,
    validate_module_loader_error_path_case,
    validate_params_io_error_path_case,
    validate_preflight_error_path_case,
)
from .synthetic_data_quality_cases import (
    validate_load_clean_df_data_quality_case,
    validate_sanitize_ohlcv_expected_behavior_case,
    validate_sanitize_ohlcv_failfast_case,
)
from .synthetic_cli_cases import (
    validate_dataset_cli_contract_case,
    validate_breakout_quality_app_simple_report_contract_case,
    validate_extended_tool_cli_contract_case,
    validate_local_regression_cli_contract_case,
    validate_package_zip_commit_test_suite_orchestration_case,
    validate_package_zip_runtime_contract_case,
    validate_run_all_cli_error_usage_contract_case,
)
from .synthetic_strategy_cases import (
    validate_model_io_schema_case,
    validate_optimizer_interrupt_export_contract_case,
    validate_optimizer_objective_export_contract_case,
    validate_optimizer_session_milestone_cache_case,
    validate_optimizer_walk_forward_policy_contract_case,
    validate_ranking_scoring_sanity_case,
    validate_score_numerator_option_case,
    validate_strategy_minimum_viability_case,
    validate_strategy_repeatability_case,
    validate_strategy_reporting_schema_compatibility_case,
)
from .synthetic_regression_cases import (
    validate_optimizer_raw_cache_rerun_consistency_case,
    validate_optimizer_replay_raw_universe_contract_case,
    validate_run_all_repeatability_case,
    validate_scan_runner_repeatability_case,
    validate_scanner_worker_repeatability_case,
)
from .synthetic_flow_cases import (
    validate_synthetic_empty_backtest_df_contract_case,
    validate_synthetic_ensemble_reentry_consensus_watchlist_case,
    validate_synthetic_fill_below_limit_based_sizing_stop_still_enters_case,
    validate_synthetic_inherited_entry_fill_must_be_above_stop_case,
)


@dataclass(frozen=True)
class SyntheticValidatorEntry:
    validator: Callable
    layer: str
    cost_class: str

    @property
    def name(self) -> str:
        return self.validator.__name__

    @property
    def impacted_modules(self) -> tuple[str, ...]:
        """Deprecated compatibility view; registry ownership is location-independent."""

        return ()


def _entry(validator, *, layer, cost_class):
    return SyntheticValidatorEntry(
        validator=validator,
        layer=layer,
        cost_class=cost_class,
    )


def get_synthetic_validator_entries():
    return [
        _entry(validate_synthetic_same_day_buy_sell_forbidden_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_intraday_reprice_forbidden_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_no_intraday_switch_after_failed_fill_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_missed_buy_no_replacement_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_exit_orders_only_for_held_positions_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_fee_tax_net_equity_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_missed_sell_accounting_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_round_trip_pnl_only_on_tail_exit_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_half_tp_full_year_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_same_bar_stop_priority_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_conservative_executable_exit_interpretation_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_extended_signal_a2_frozen_plan_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_empty_backtest_df_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_init_sl_single_source_runtime_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_candidate_order_fill_layer_separation_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_portfolio_entry_preserves_fill_based_first_actionable_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_fill_below_limit_based_sizing_stop_still_enters_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_inherited_entry_fill_must_be_above_stop_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_ensemble_reentry_consensus_watchlist_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_extended_miss_buy_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_competing_candidates_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_same_day_sell_block_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_unexecutable_half_tp_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_rotation_t_plus_one_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_proj_cost_cash_capped_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_history_ev_threshold_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_portfolio_history_filter_only_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_lookahead_prev_day_only_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_setup_index_prev_day_only_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_pit_same_day_exit_excluded_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_pit_multiple_same_day_exits_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_single_backtest_not_gated_by_own_history_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_single_backtest_uses_compounding_capital_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_synthetic_param_guardrail_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_policy_single_source_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_active_legacy_model_isolation_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_chronological_embargo_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_continuous_target_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_continuous_ranker_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_all_event_no_time_ranker_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_pairwise_ranker_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_daily_full_list_ndcg_pairwise_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_full_horizon_target_components_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_reusable_model_component_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_low_adverse_target_component_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_conditional_mfe_safety_single_model_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_reverse_conditional_mfe_ab_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_safety_raw_mfe_duo_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_safety_raw_mfe_hmhs_tri_head_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_hmhs_single_head_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_nonlinear_hmhs_head_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_joint_min_target_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_joint_attention_pool_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_modern_tcn_joint_min_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_patch_transformer_joint_min_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13aa_patch_transformer_h_target_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13ab_first_breach_pure_mfe_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13ac_predicted_upside_conditional_safety_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13ad_predicted_safety_conditional_mfe_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13ae_predicted_safety_context_pure_mfe_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13af_high_safety_weighted_pure_mfe_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_mr13ag_mfe_winner_safety_weighted_pure_mfe_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_multi_dl_ranker_architecture_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_point_in_time_score_builder_contract_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_pit_training_performance_semantics_case, layer="core_invariant", cost_class="fast"),
        _entry(validate_breakout_quality_selection_point_in_time_score_sort_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_binary_dl_param_adaptation_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_trade_path_label_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_single_seed_single_entry_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_strategy_compare_config_driven_app_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_mr13z_c75_conversion_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_strategy_compare_resolved_plan_transition_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_daily_pit_strategy_runtime_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_runtime_integration_gate_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_audit_framework_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_runtime_artifact_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_breakout_quality_strategy_comparison_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_breakout_quality_strategy_readable_report_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_breakout_quality_legacy_research_cleanup_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_price_utils_unit_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_signal_utils_unit_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_history_filters_unit_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_portfolio_stats_unit_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_ledger_conservation_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_cost_basis_allocation_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_tick_limit_integer_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_cash_risk_boundary_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_single_vs_portfolio_parity_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_display_derived_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_exact_accounting_display_leg_reconciliation_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_independent_oracle_golden_case, layer="unit_boundary", cost_class="fast"),
        _entry(validate_research_report_contract_freeze_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_registry_checklist_entry_consistency_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_t_formal_command_single_entry_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_done_test_summary_markdown_structure_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_t_single_entry_delimiter_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_g_transition_format_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_g_ordering_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_g_new_transition_first_occurrence_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_g_transition_sequence_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_summary_tables_sorted_by_id_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_synthetic_cases_import_target_resolution_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_quick_gate_synthetic_registry_import_targets_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_single_backtest_stats_legacy_schema_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_debug_backtest_entry_cash_path_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_price_utils_array_tick_normalization_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_test_suite_help_text_mentions_stable_theme_tokens_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_portfolio_rotation_mark_to_market_return_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_portfolio_core_module_boundary_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_synthetic_registry_metadata_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_core_trading_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_critical_helper_single_source_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_policy_contract_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_test_suite_orchestrator_coverage_targets_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_formal_step_entry_coverage_targets_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_formal_step_implementation_coverage_targets_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_critical_file_coverage_minimum_gate_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_meta_quality_coverage_threshold_uses_target_scope_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_critical_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_entry_path_critical_coverage_gate_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_peak_traced_memory_tracker_context_management_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_known_bad_fault_injection_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_cmd_document_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_gui_workbench_documentation_sync_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_architecture_workbench_entry_file_tree_sync_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_model_param_source_resolution_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_architecture_local_regression_meta_quality_file_tree_sync_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_trade_analysis_legacy_naming_documentation_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_trade_analysis_canonical_alias_export_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_validate_runtime_tmp_output_staging_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_no_legacy_app_entry_doc_references_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_app_thin_wrapper_export_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_no_reverse_app_layer_dependencies_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_no_top_level_import_cycles_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_single_formal_test_entry_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_checklist_physical_trading_principles_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_specific_pass_only_exception_traceability_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_broad_exception_traceability_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_gui_tcl_fallback_traceability_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_optional_dependency_fallback_traceability_contract_case, layer="meta_contract", cost_class="fast"),
        _entry(validate_display_reporting_sanity_case, layer="output_contract", cost_class="fast"),
        _entry(validate_validate_console_summary_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_portfolio_yearly_report_schema_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_failure_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_manifest_failure_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_optional_dataset_skip_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_checklist_status_sync_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_meta_quality_guardrail_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_meta_quality_memory_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_preflight_failure_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_dataset_prepare_failure_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_test_suite_summary_unreadable_payload_reporting_case, layer="output_contract", cost_class="fast"),
        _entry(validate_issue_excel_report_schema_case, layer="output_contract", cost_class="fast"),
        _entry(validate_portfolio_export_report_artifacts_case, layer="output_contract", cost_class="fast"),
        _entry(validate_output_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_dataset_fingerprint_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_reduced_dataset_dynamic_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_run_all_dataset_prepare_pass_main_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_atomic_write_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_atomic_write_retry_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_atomic_write_cleanup_error_preserves_root_exception_case, layer="output_contract", cost_class="fast"),
        _entry(validate_validate_summary_atomic_write_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_portfolio_sim_prepared_tool_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_scanner_prepared_tool_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_scanner_reference_clean_df_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_scanner_live_capital_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_debug_trade_log_prepared_tool_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_debug_trade_log_chart_context_optional_case, layer="output_contract", cost_class="fast"),
        _entry(validate_debug_chart_payload_without_html_export_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_debug_empty_price_df_chart_payload_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_chart_payload_optional_overlay_keys_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_workbench_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_embedded_chart_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_chart_workspace_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_mouse_navigation_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_dark_theme_and_keyboard_pan_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_navigation_canvas_stub_cleanup_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_navigation_canvas_stub_toolbar_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_record_signal_annotation_meta_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_chart_recent_view_signal_overlay_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_workbench_theme_accent_symbol_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_scanner_console_and_latest_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_sidebar_latest_preview_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_single_stock_refined_visual_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_extended_preview_continuity_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_chart_margin_and_latest_extended_preview_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_signal_annotation_and_forced_close_visual_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_buy_signal_annotation_anchor_price_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_trade_marker_and_tp_visual_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_trade_count_and_sidebar_sync_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_trade_box_capital_and_round_trip_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_latest_raw_signal_preview_helper_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_gui_chart_overlay_layout_and_pan_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_debug_entry_plan_marker_optional_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_tool_module_path_normalization_case, layer="output_contract", cost_class="fast"),
        _entry(validate_module_path_normalizer_accepts_path_objects_case, layer="output_contract", cost_class="fast"),
        _entry(validate_module_loader_project_root_string_patch_case, layer="output_contract", cost_class="fast"),
        _entry(validate_local_regression_summary_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_meta_quality_performance_memory_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_meta_quality_reuses_existing_coverage_artifacts_case, layer="output_contract", cost_class="fast"),
        _entry(validate_run_all_preflight_early_failure_dataset_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_run_all_manifest_failure_master_summary_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_artifact_lifecycle_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_quick_gate_bare_except_guard_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_quick_gate_output_path_guard_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_dataset_prepare_fallback_write_traceability_case, layer="output_contract", cost_class="fast"),
        _entry(validate_console_tail_read_error_traceability_case, layer="output_contract", cost_class="fast"),
        _entry(validate_single_ticker_compounding_parity_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_params_io_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_module_loader_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_preflight_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_downloader_market_date_fallback_case, layer="error_path", cost_class="fast"),
        _entry(validate_downloader_universe_fetch_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_downloader_universe_screening_init_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_downloader_sync_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_downloader_main_error_path_case, layer="error_path", cost_class="fast"),
        _entry(validate_sanitize_ohlcv_expected_behavior_case, layer="data_quality", cost_class="fast"),
        _entry(validate_sanitize_ohlcv_failfast_case, layer="data_quality", cost_class="fast"),
        _entry(validate_load_clean_df_data_quality_case, layer="data_quality", cost_class="fast"),
        _entry(validate_breakout_quality_app_simple_report_contract_case, layer="output_contract", cost_class="fast"),
        _entry(validate_dataset_cli_contract_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_local_regression_cli_contract_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_package_zip_runtime_contract_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_package_zip_commit_test_suite_orchestration_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_run_all_cli_error_usage_contract_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_extended_tool_cli_contract_case, layer="cli_contract", cost_class="fast"),
        _entry(validate_model_io_schema_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_optimizer_interrupt_export_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_optimizer_objective_export_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_optimizer_session_milestone_cache_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_optimizer_walk_forward_policy_contract_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_ranking_scoring_sanity_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_score_numerator_option_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_use_compounding_failfast_guardrail_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_strategy_repeatability_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_strategy_minimum_viability_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_strategy_reporting_schema_compatibility_case, layer="strategy_contract", cost_class="fast"),
        _entry(validate_scanner_worker_repeatability_case, layer="regression_contract", cost_class="medium"),
        _entry(validate_scan_runner_repeatability_case, layer="regression_contract", cost_class="medium"),
        _entry(validate_optimizer_raw_cache_rerun_consistency_case, layer="regression_contract", cost_class="medium"),
        _entry(validate_optimizer_replay_raw_universe_contract_case, layer="regression_contract", cost_class="medium"),
        _entry(validate_run_all_repeatability_case, layer="regression_contract", cost_class="medium"),
    ]


def get_synthetic_validator_metadata():
    return [
        {
            "name": entry.name,
            "layer": entry.layer,
            "cost_class": entry.cost_class,
            "impacted_modules": list(entry.impacted_modules),
        }
        for entry in get_synthetic_validator_entries()
    ]


def get_synthetic_validators():
    return [entry.validator for entry in get_synthetic_validator_entries()]


def run_synthetic_consistency_suite(base_params):
    all_results = []
    summaries = []
    validator_entries = get_synthetic_validator_entries()

    for entry in validator_entries:
        results, summary = entry.validator(base_params)
        all_results.extend(results)
        summaries.append(summary)

    return all_results, summaries
