from dataclasses import dataclass
from typing import Callable

from .synthetic_param_cases import (
    validate_synthetic_history_ev_threshold_case,
    validate_synthetic_lookahead_prev_day_only_case,
    validate_synthetic_param_guardrail_case,
    validate_synthetic_pit_multiple_same_day_exits_case,
    validate_synthetic_pit_same_day_exit_excluded_case,
    validate_synthetic_portfolio_history_filter_only_case,
    validate_synthetic_proj_cost_cash_capped_case,
    validate_synthetic_single_backtest_uses_compounding_capital_case,
    validate_synthetic_single_backtest_not_gated_by_own_history_case,
    validate_use_compounding_failfast_guardrail_case,
)
from .synthetic_history_cases import (
    validate_synthetic_setup_index_prev_day_only_case,
)
from .synthetic_portfolio_cases import (
    validate_synthetic_candidate_order_fill_layer_separation_case,
    validate_synthetic_competing_candidates_case,
    validate_synthetic_exit_orders_only_for_held_positions_case,
    validate_synthetic_extended_miss_buy_case,
    validate_synthetic_fee_tax_net_equity_case,
    validate_synthetic_half_tp_full_year_case,
    validate_synthetic_intraday_reprice_forbidden_case,
    validate_synthetic_missed_buy_no_replacement_case,
    validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case,
    validate_synthetic_missed_sell_accounting_case,
    validate_synthetic_no_intraday_switch_after_failed_fill_case,
    validate_synthetic_rotation_t_plus_one_case,
    validate_synthetic_round_trip_pnl_only_on_tail_exit_case,
    validate_synthetic_same_bar_stop_priority_case,
    validate_synthetic_same_day_buy_sell_forbidden_case,
    validate_synthetic_same_day_sell_block_case,
    validate_synthetic_unexecutable_half_tp_case,
)
from .synthetic_unit_cases import (
    validate_history_filters_unit_case,
    validate_independent_oracle_golden_case,
    validate_portfolio_stats_unit_case,
    validate_price_utils_unit_case,
)
from .synthetic_meta_cases import (
    validate_checklist_no_legacy_d_section_case,
    validate_checklist_no_legacy_f1_section_case,
    validate_checklist_f2_single_entry_delimiter_case,
    validate_checklist_g_single_note_entry_delimiter_case,
    validate_checklist_g_transition_format_case,
    validate_checklist_g_ordering_case,
    validate_checklist_g_new_transition_first_occurrence_case,
    validate_checklist_first_nonempty_line_case,
    validate_checklist_g_note_validate_reference_exists_case,
    validate_checklist_summary_tables_sorted_by_id_case,
    validate_synthetic_meta_cases_summary_value_accessor_contract_case,
    validate_synthetic_case_numpy_alias_import_contract_case,
    validate_synthetic_case_numpy_alias_scan_ignores_string_literals_contract_case,
    validate_synthetic_case_chart_navigation_binder_import_contract_case,
    validate_cmd_document_contract_case,
    validate_core_trading_modules_in_coverage_targets_case,
    validate_critical_helper_single_source_contract_case,
    validate_policy_contract_modules_in_coverage_targets_case,
    validate_coverage_threshold_floor_case,
    validate_critical_coverage_threshold_floor_case,
    validate_critical_file_coverage_minimum_gate_case,
    validate_entry_path_critical_coverage_gate_case,
    validate_formal_step_entry_coverage_targets_case,
    validate_formal_step_implementation_coverage_targets_case,
    validate_known_bad_fault_injection_case,
    validate_no_legacy_app_entry_doc_references_case,
    validate_app_thin_wrapper_export_contract_case,
    validate_no_reverse_app_layer_dependencies_case,
    validate_no_top_level_import_cycles_case,
    validate_peak_traced_memory_tracker_context_management_case,
    validate_project_settings_dynamic_test_boundary_case,
    validate_registry_checklist_entry_consistency_case,
    validate_single_formal_test_entry_contract_case,
    validate_synthetic_registry_metadata_contract_case,
    validate_test_suite_orchestrator_coverage_targets_case,
)
from .synthetic_display_cases import validate_display_reporting_sanity_case
from .synthetic_reporting_cases import (
    validate_issue_excel_report_schema_case,
    validate_portfolio_export_report_artifacts_case,
    validate_portfolio_yearly_report_schema_case,
    validate_test_suite_summary_checklist_status_sync_case,
    validate_test_suite_summary_dataset_prepare_failure_reporting_case,
    validate_test_suite_summary_failure_reporting_case,
    validate_test_suite_summary_manifest_failure_reporting_case,
    validate_test_suite_summary_meta_quality_guardrail_reporting_case,
    validate_test_suite_summary_meta_quality_memory_reporting_case,
    validate_test_suite_summary_optional_dataset_skip_case,
    validate_test_suite_summary_preflight_failure_reporting_case,
    validate_test_suite_summary_reporting_case,
    validate_test_suite_summary_unreadable_payload_reporting_case,
    validate_validate_console_summary_reporting_case,
)
from .synthetic_contract_cases import (
    validate_artifact_lifecycle_contract_case,
    validate_atomic_write_contract_case,
    validate_atomic_write_retry_contract_case,
    validate_atomic_write_cleanup_error_preserves_root_exception_case,
    validate_validate_summary_atomic_write_contract_case,
    validate_dataset_fingerprint_contract_case,
    validate_reduced_dataset_dynamic_contract_case,
    validate_run_all_dataset_prepare_pass_main_contract_case,
    validate_local_regression_summary_contract_case,
    validate_meta_quality_reuses_existing_coverage_artifacts_case,
    validate_debug_trade_log_chart_context_optional_case,
    validate_debug_trade_log_prepared_tool_contract_case,
    validate_debug_chart_payload_without_html_export_contract_case,
    validate_chart_payload_optional_overlay_keys_contract_case,
    validate_gui_embedded_chart_contract_case,
    validate_gui_chart_workspace_contract_case,
    validate_gui_mouse_navigation_contract_case,
    validate_gui_dark_theme_and_keyboard_pan_contract_case,
    validate_gui_navigation_canvas_stub_cleanup_contract_case,
    validate_gui_navigation_canvas_stub_toolbar_contract_case,
    validate_gui_chart_recent_view_signal_overlay_contract_case,
    validate_debug_entry_plan_marker_optional_contract_case,
    validate_gui_workbench_contract_case,
    validate_tool_module_path_normalization_case,
    validate_module_path_normalizer_accepts_path_objects_case,
    validate_module_loader_project_root_string_patch_case,
    validate_meta_quality_performance_memory_contract_case,
    validate_output_contract_case,
    validate_portfolio_sim_prepared_tool_contract_case,
    validate_quick_gate_bare_except_guard_contract_case,
    validate_quick_gate_output_path_guard_contract_case,
    validate_run_all_manifest_failure_master_summary_contract_case,
    validate_run_all_preflight_early_failure_dataset_contract_case,
    validate_scanner_prepared_tool_contract_case,
    validate_scanner_reference_clean_df_contract_case,
    validate_scanner_live_capital_contract_case,
    validate_dataset_prepare_fallback_write_traceability_case,
    validate_console_tail_read_error_traceability_case,
    validate_single_ticker_compounding_parity_contract_case,
)
from .synthetic_error_cases import (
    validate_downloader_main_error_path_case,
    validate_downloader_market_date_fallback_case,
    validate_downloader_sync_error_path_case,
    validate_downloader_universe_fetch_error_path_case,
    validate_downloader_universe_screening_init_error_path_case,
    validate_module_loader_error_path_case,
    validate_params_io_error_path_case,
    validate_preflight_error_path_case,
)
from .synthetic_data_quality_cases import (
    validate_load_clean_df_data_quality_case,
    validate_sanitize_ohlcv_expected_behavior_case,
    validate_sanitize_ohlcv_failfast_case,
)
from .synthetic_cli_cases import (
    validate_dataset_cli_contract_case,
    validate_extended_tool_cli_contract_case,
    validate_local_regression_cli_contract_case,
    validate_package_zip_commit_test_suite_orchestration_case,
    validate_package_zip_runtime_contract_case,
    validate_run_all_cli_error_usage_contract_case,
)
from .synthetic_strategy_cases import (
    validate_model_io_schema_case,
    validate_optimizer_interrupt_export_contract_case,
    validate_optimizer_objective_export_contract_case,
    validate_ranking_scoring_sanity_case,
    validate_score_numerator_option_case,
    validate_strategy_minimum_viability_case,
    validate_strategy_repeatability_case,
    validate_strategy_reporting_schema_compatibility_case,
)
from .synthetic_regression_cases import (
    validate_optimizer_raw_cache_rerun_consistency_case,
    validate_run_all_repeatability_case,
    validate_scan_runner_repeatability_case,
    validate_scanner_worker_repeatability_case,
)


@dataclass(frozen=True)
class SyntheticValidatorEntry:
    validator: Callable
    layer: str
    cost_class: str
    impacted_modules: tuple[str, ...]

    @property
    def name(self) -> str:
        return self.validator.__name__


def _entry(validator, *, layer, cost_class, impacted_modules):
    return SyntheticValidatorEntry(
        validator=validator,
        layer=layer,
        cost_class=cost_class,
        impacted_modules=tuple(impacted_modules),
    )


def get_synthetic_validator_entries():
    return [
        _entry(validate_synthetic_same_day_buy_sell_forbidden_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/backtest_core.py", "core/portfolio_engine.py")),
        _entry(validate_synthetic_intraday_reprice_forbidden_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_entries.py", "core/trade_plans.py")),
        _entry(validate_synthetic_no_intraday_switch_after_failed_fill_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_missed_buy_no_replacement_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_engine.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_exit_orders_only_for_held_positions_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/position_step.py")),
        _entry(validate_synthetic_fee_tax_net_equity_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/price_utils.py", "core/portfolio_stats.py")),
        _entry(validate_synthetic_missed_sell_accounting_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "tools/debug/trade_log.py")),
        _entry(validate_synthetic_round_trip_pnl_only_on_tail_exit_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_stats.py", "tools/debug/trade_log.py")),
        _entry(validate_synthetic_half_tp_full_year_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_stats.py", "tools/portfolio_sim/reporting.py")),
        _entry(validate_synthetic_same_bar_stop_priority_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/position_step.py", "core/backtest_core.py")),
        _entry(validate_synthetic_candidate_order_fill_layer_separation_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_entries.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_non_candidate_setup_does_not_seed_extended_signal_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_candidates.py", "core/extended_signals.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_extended_miss_buy_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/extended_signals.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_competing_candidates_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_candidates.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_same_day_sell_block_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_unexecutable_half_tp_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/position_step.py", "tools/debug/trade_log.py")),
        _entry(validate_synthetic_rotation_t_plus_one_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_exits.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_proj_cost_cash_capped_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/buy_sort.py", "core/portfolio_entries.py")),
        _entry(validate_synthetic_history_ev_threshold_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_portfolio_history_filter_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_lookahead_prev_day_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_fast_data.py", "core/portfolio_engine.py")),
        _entry(validate_synthetic_setup_index_prev_day_only_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/portfolio_fast_data.py", "core/extended_signals.py")),
        _entry(validate_synthetic_pit_same_day_exit_excluded_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_pit_multiple_same_day_exits_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/history_filters.py", "core/portfolio_fast_data.py")),
        _entry(validate_synthetic_single_backtest_not_gated_by_own_history_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/backtest_core.py", "tools/scanner/stock_processor.py")),
        _entry(validate_synthetic_single_backtest_uses_compounding_capital_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/capital_policy.py", "core/backtest_core.py", "core/backtest_finalize.py", "tools/debug/backtest.py")),
        _entry(validate_synthetic_param_guardrail_case, layer="core_invariant", cost_class="fast", impacted_modules=("core/strategy_params.py", "config/execution_policy.py", "tools/optimizer/objective_profiles.py")),
        _entry(validate_price_utils_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/price_utils.py",)),
        _entry(validate_history_filters_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/history_filters.py",)),
        _entry(validate_portfolio_stats_unit_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/portfolio_stats.py",)),
        _entry(validate_independent_oracle_golden_case, layer="unit_boundary", cost_class="fast", impacted_modules=("core/price_utils.py", "core/history_filters.py", "core/portfolio_stats.py")),
        _entry(validate_registry_checklist_entry_consistency_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/validate/synthetic_cases.py")),
        _entry(validate_checklist_no_legacy_d_section_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_no_legacy_f1_section_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_f2_single_entry_delimiter_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_transition_format_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_ordering_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_g_new_transition_first_occurrence_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_checklist_first_nonempty_line_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_checklist_summary_tables_sorted_by_id_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_meta_cases_summary_value_accessor_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_case_numpy_alias_import_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_contract_cases.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_case_numpy_alias_scan_ignores_string_literals_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_meta_cases.py",)),
_entry(validate_synthetic_case_chart_navigation_binder_import_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_meta_cases.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_checklist_g_note_validate_reference_exists_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_synthetic_registry_metadata_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_cases.py",)),
        _entry(validate_core_trading_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_critical_helper_single_source_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("core/price_utils.py", "core/capital_policy.py", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_policy_contract_modules_in_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/meta_quality_targets.py", "tools/validate/synthetic_meta_cases.py", "core/capital_policy.py", "core/strategy_params.py", "core/params_io.py", "config/execution_policy.py", "config/training_policy.py")),
        _entry(validate_test_suite_orchestrator_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_formal_step_entry_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/formal_pipeline.py", "tools/local_regression/meta_quality_targets.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_formal_step_implementation_coverage_targets_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/meta_quality_targets.py", "tools/validate/main.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_critical_file_coverage_minimum_gate_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/manifest.json", "tools/local_regression/common.py")),
        _entry(validate_critical_coverage_threshold_floor_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/manifest.json", "tools/local_regression/common.py")),
        _entry(validate_entry_path_critical_coverage_gate_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_peak_traced_memory_tracker_context_management_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_chain_checks.py", "tools/local_regression/run_meta_quality.py", "tools/local_regression/run_ml_smoke.py", "tools/local_regression/run_quick_gate.py", "tools/validate/main.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_known_bad_fault_injection_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_meta_cases.py",)),
        _entry(validate_cmd_document_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md",)),
        _entry(validate_no_legacy_app_entry_doc_references_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/CMD.md", "doc/ARCHITECTURE.md", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_app_thin_wrapper_export_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("apps/portfolio_sim.py", "apps/vip_scanner.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_no_reverse_app_layer_dependencies_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/ARCHITECTURE.md", "tools/validate/meta_contracts.py")),
        _entry(validate_no_top_level_import_cycles_case, layer="meta_contract", cost_class="fast", impacted_modules=("tools/validate/meta_contracts.py",)),
        _entry(validate_single_formal_test_entry_contract_case, layer="meta_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/formal_pipeline.py")),
        _entry(validate_project_settings_dynamic_test_boundary_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/PROJECT_SETTINGS.md", "tools/validate/meta_contracts.py", "tools/validate/synthetic_meta_cases.py")),
        _entry(validate_checklist_g_single_note_entry_delimiter_case, layer="meta_contract", cost_class="fast", impacted_modules=("doc/TEST_SUITE_CHECKLIST.md", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_display_reporting_sanity_case, layer="output_contract", cost_class="fast", impacted_modules=("core/display.py", "tools/scanner/reporting.py")),
        _entry(validate_validate_console_summary_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py",)),
        _entry(validate_portfolio_yearly_report_schema_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/reporting.py",)),
        _entry(validate_test_suite_summary_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_manifest_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_all.py")),
        _entry(validate_test_suite_summary_optional_dataset_skip_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_checklist_status_sync_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "doc/TEST_SUITE_CHECKLIST.md")),
        _entry(validate_test_suite_summary_meta_quality_guardrail_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_test_suite_summary_meta_quality_memory_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_meta_quality.py")),
        _entry(validate_test_suite_summary_preflight_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_test_suite_summary_dataset_prepare_failure_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/local_regression/run_all.py")),
        _entry(validate_test_suite_summary_unreadable_payload_reporting_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/test_suite.py",)),
        _entry(validate_issue_excel_report_schema_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py",)),
        _entry(validate_portfolio_export_report_artifacts_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/reporting.py",)),
        _entry(validate_output_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/validate/reporting.py")),
        _entry(validate_dataset_fingerprint_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/local_regression/run_all.py")),
        _entry(validate_reduced_dataset_dynamic_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_run_all_dataset_prepare_pass_main_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_atomic_write_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_atomic_write_retry_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_atomic_write_cleanup_error_preserves_root_exception_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_validate_summary_atomic_write_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/reporting.py", "tools/local_regression/common.py")),
        _entry(validate_portfolio_sim_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/portfolio_sim/main.py",)),
        _entry(validate_scanner_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/scanner/scan_runner.py",)),
        _entry(validate_scanner_reference_clean_df_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/real_case_io.py", "tools/scanner/stock_processor.py")),
        _entry(validate_scanner_live_capital_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("core/capital_policy.py", "config/execution_policy.py", "core/price_utils.py", "tools/scanner/stock_processor.py")),
        _entry(validate_debug_trade_log_prepared_tool_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/trade_log.py",)),
        _entry(validate_debug_trade_log_chart_context_optional_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/charting.py", "tools/debug/trade_log.py")),
        _entry(validate_debug_chart_payload_without_html_export_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/backtest.py", "tools/debug/reporting.py", "tools/debug/trade_log.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_chart_payload_optional_overlay_keys_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_workbench_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("apps/gui.py", "tools/gui/main.py", "tools/gui/workbench.py", "tools/gui/single_stock_inspector.py", "tools/debug/trade_log.py")),
        _entry(validate_gui_embedded_chart_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/charting.py", "tools/gui/single_stock_inspector.py", "tools/gui/workbench.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_chart_workspace_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/gui/single_stock_inspector.py", "tools/gui/workbench.py", "tools/debug/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_mouse_navigation_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/gui/single_stock_inspector.py", "tools/debug/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_dark_theme_and_keyboard_pan_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/gui/workbench.py", "tools/gui/single_stock_inspector.py", "tools/debug/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_gui_navigation_canvas_stub_cleanup_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_contract_cases.py",)),
        _entry(validate_gui_navigation_canvas_stub_toolbar_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_contract_cases.py",)),
        _entry(validate_gui_chart_recent_view_signal_overlay_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/gui/single_stock_inspector.py", "tools/debug/charting.py", "tools/debug/backtest.py", "tools/debug/entry_flow.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_debug_entry_plan_marker_optional_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/debug/entry_flow.py", "tools/debug/charting.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_tool_module_path_normalization_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/external_tool_checks.py")),
        _entry(validate_module_path_normalizer_accepts_path_objects_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/synthetic_contract_cases.py")),
        _entry(validate_module_loader_project_root_string_patch_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/validate/module_loader.py", "tools/validate/synthetic_contract_cases.py", "tools/validate/synthetic_error_cases.py")),
        _entry(validate_local_regression_summary_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py", "tools/validate/reporting.py")),
        _entry(validate_meta_quality_performance_memory_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py",)),
        _entry(validate_meta_quality_reuses_existing_coverage_artifacts_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_meta_quality.py", "tools/validate/main.py")),
        _entry(validate_run_all_preflight_early_failure_dataset_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_run_all_manifest_failure_master_summary_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_artifact_lifecycle_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_quick_gate_bare_except_guard_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_quick_gate.py",)),
        _entry(validate_quick_gate_output_path_guard_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_quick_gate.py", "core/output_paths.py", "core/log_utils.py")),
        _entry(validate_dataset_prepare_fallback_write_traceability_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_console_tail_read_error_traceability_case, layer="output_contract", cost_class="fast", impacted_modules=("tools/local_regression/common.py",)),
        _entry(validate_single_ticker_compounding_parity_contract_case, layer="output_contract", cost_class="fast", impacted_modules=("core/capital_policy.py", "core/backtest_core.py", "core/portfolio_engine.py", "tools/validate/real_case_runners.py")),
        _entry(validate_params_io_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("core/params_io.py",)),
        _entry(validate_module_loader_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/validate/module_loader.py",)),
        _entry(validate_preflight_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/validate/preflight_env.py",)),
        _entry(validate_downloader_market_date_fallback_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_universe_fetch_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_universe_screening_init_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/universe.py",)),
        _entry(validate_downloader_sync_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/sync.py",)),
        _entry(validate_downloader_main_error_path_case, layer="error_path", cost_class="fast", impacted_modules=("tools/downloader/main.py",)),
        _entry(validate_sanitize_ohlcv_expected_behavior_case, layer="data_quality", cost_class="fast", impacted_modules=("core/data_utils.py",)),
        _entry(validate_sanitize_ohlcv_failfast_case, layer="data_quality", cost_class="fast", impacted_modules=("core/data_utils.py",)),
        _entry(validate_load_clean_df_data_quality_case, layer="data_quality", cost_class="fast", impacted_modules=("tools/validate/real_case_io.py", "core/data_utils.py")),
        _entry(validate_dataset_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("tools/validate/cli.py",)),
        _entry(validate_local_regression_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py", "tools/local_regression/run_quick_gate.py")),
        _entry(validate_package_zip_runtime_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/package_zip.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_package_zip_commit_test_suite_orchestration_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/package_zip.py", "apps/test_suite.py", "tools/validate/synthetic_cli_cases.py")),
        _entry(validate_run_all_cli_error_usage_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("tools/local_regression/run_all.py",)),
        _entry(validate_extended_tool_cli_contract_case, layer="cli_contract", cost_class="fast", impacted_modules=("apps/test_suite.py", "tools/optimizer/main.py", "tools/scanner/scan_runner.py")),
        _entry(validate_model_io_schema_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/optimizer/study_utils.py", "tools/scanner/stock_processor.py")),
        _entry(validate_optimizer_interrupt_export_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/optimizer/main.py", "tools/optimizer/runtime.py")),
        _entry(validate_optimizer_objective_export_contract_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/optimizer/objective_runner.py", "tools/optimizer/runtime.py", "tools/optimizer/study_utils.py")),
        _entry(validate_ranking_scoring_sanity_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/buy_sort.py", "core/portfolio_stats.py")),
        _entry(validate_score_numerator_option_case, layer="strategy_contract", cost_class="fast", impacted_modules=("config/training_policy.py", "core/portfolio_stats.py", "core/strategy_dashboard.py", "core/scanner_display.py")),
        _entry(validate_use_compounding_failfast_guardrail_case, layer="strategy_contract", cost_class="fast", impacted_modules=("core/strategy_params.py", "core/params_io.py", "config/execution_policy.py")),
        _entry(validate_strategy_repeatability_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "tools/optimizer/objective_runner.py", "tools/scanner/stock_processor.py")),
        _entry(validate_strategy_minimum_viability_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "core/strategy_dashboard.py", "tools/scanner/reporting.py", "tools/portfolio_sim/reporting.py")),
        _entry(validate_strategy_reporting_schema_compatibility_case, layer="strategy_contract", cost_class="fast", impacted_modules=("tools/validate/synthetic_strategy_cases.py", "tools/optimizer/runtime.py", "tools/portfolio_sim/reporting.py", "tools/scanner/stock_processor.py")),
        _entry(validate_scanner_worker_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/scanner/stock_processor.py",)),
        _entry(validate_scan_runner_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/scanner/scan_runner.py",)),
        _entry(validate_optimizer_raw_cache_rerun_consistency_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/optimizer/raw_cache.py",)),
        _entry(validate_run_all_repeatability_case, layer="regression_contract", cost_class="medium", impacted_modules=("tools/local_regression/run_all.py",)),
    ]


def get_synthetic_validator_metadata():
    return [
        {
            "name": entry.name,
            "layer": entry.layer,
            "cost_class": entry.cost_class,
            "impacted_modules": list(entry.impacted_modules),
        }
        for entry in get_synthetic_validator_entries()
    ]


def get_synthetic_validators():
    return [entry.validator for entry in get_synthetic_validator_entries()]


def run_synthetic_consistency_suite(base_params):
    all_results = []
    summaries = []
    validator_entries = get_synthetic_validator_entries()

    for entry in validator_entries:
        results, summary = entry.validator(base_params)
        all_results.extend(results)
        summaries.append(summary)

    return all_results, summaries
