from strategies.breakout.search_space import build_trial_params
from tools.optimizer.study_utils import INVALID_TRIAL_VALUE


def build_initial_profile_row(trial_number, prep_wall_sec, prep_profile):
    return {
        "trial_number": trial_number + 1,
        "objective_wall_sec": 0.0,
        "prep_wall_sec": prep_wall_sec,
        "prep_worker_total_sum_sec": prep_profile["worker_total_sum_sec"],
        "prep_worker_copy_sum_sec": prep_profile["copy_sum_sec"],
        "prep_worker_generate_signals_sum_sec": prep_profile["generate_signals_sum_sec"],
        "prep_worker_assign_sum_sec": prep_profile["assign_sum_sec"],
        "prep_worker_run_backtest_sum_sec": prep_profile["run_backtest_sum_sec"],
        "prep_worker_to_dict_sum_sec": prep_profile["to_dict_sum_sec"],
        "prep_ok_count": prep_profile["ok_count"],
        "prep_fail_count": prep_profile["fail_count"],
        "prep_avg_per_ok_sec": (prep_profile["prep_total_sum_sec"] / prep_profile["ok_count"]) if prep_profile["ok_count"] > 0 else 0.0,
        "sort_dates_sec": 0.0,
        "portfolio_wall_sec": 0.0,
        "portfolio_total_sec": 0.0,
        "portfolio_ticker_dates_sec": 0.0,
        "portfolio_build_trade_index_sec": 0.0,
        "portfolio_day_loop_sec": 0.0,
        "portfolio_candidate_scan_sec": 0.0,
        "portfolio_rotation_sec": 0.0,
        "portfolio_settle_sec": 0.0,
        "portfolio_buy_sec": 0.0,
        "portfolio_equity_mark_sec": 0.0,
        "portfolio_closeout_sec": 0.0,
        "portfolio_curve_stats_sec": 0.0,
        "filter_rules_sec": 0.0,
        "score_calc_sec": 0.0,
        "ret_pct": 0.0,
        "mdd": 0.0,
        "trade_count": 0,
        "annual_return_pct": 0.0,
        "annual_trades": 0.0,
        "reserved_buy_fill_rate": 0.0,
        "full_year_count": 0,
        "min_full_year_return_pct": 0.0,
        "m_win_rate": 0.0,
        "r_squared": 0.0,
        "base_score": 0.0,
        "trial_value": INVALID_TRIAL_VALUE,
        "fail_reason": "",
    }
