"""User-adjustable breakout strategy policy values."""

from __future__ import annotations

BREAKOUT_DEFAULT_HIGH_LEN = 201
BREAKOUT_HIGH_LEN_SEARCH_MIN = 60
BREAKOUT_HIGH_LEN_SEARCH_MAX = 350
BREAKOUT_HIGH_LEN_SEARCH_STEP = 5

__all__ = [
    "BREAKOUT_DEFAULT_HIGH_LEN",
    "BREAKOUT_HIGH_LEN_SEARCH_MAX",
    "BREAKOUT_HIGH_LEN_SEARCH_MIN",
    "BREAKOUT_HIGH_LEN_SEARCH_STEP",
]
