"""User-adjustable optimizer execution/performance policy values.

These knobs may change execution strategy or resource use, but must not change
sample membership/order, seeds, optimizer updates, loss, determinism, or other
scientific semantics. Runtime resolution belongs to ``core.training_performance``.
"""

# Rolling fold parallelism.
OPTIMIZER_ROLLING_FOLD_WORKERS = "fold_count"  # "fold_count" / "auto" or a positive integer
OPTIMIZER_ROLLING_PARALLEL_PREP_CACHE_MAX_ITEMS = 0
OPTIMIZER_FEATURE_BANK_MAX_ITEMS = 1024
OPTIMIZER_TIMING_MODE_DEFAULT_TRIALS = 3

# Random-seed ensemble parallelism.
OPTIMIZER_RANDOM_SEED_ENSEMBLE_PARALLEL_WORKERS = "auto"
OPTIMIZER_RANDOM_SEED_ENSEMBLE_PARALLEL_BACKEND = "process"

# Parallelism inside one optimizer search unit.
OPTIMIZER_SINGLE_FOLD_SEARCH_PARALLEL_TRIALS = 8
OPTIMIZER_SINGLE_FOLD_ALLOW_TPE_PARALLEL_SEARCH = False
OPTIMIZER_SINGLE_FOLD_LOCAL_MIN_PARALLEL_WORKERS = 4
OPTIMIZER_SINGLE_FOLD_LOCAL_MIN_PARALLEL_MAX_WORKERS = 4
OPTIMIZER_SINGLE_FOLD_LOCAL_MIN_PROCESS_WORKERS = 0

# Policy replay execution strategy.
OPTIMIZER_POLICY_REPLAY_PARALLEL_WORKERS = 2
OPTIMIZER_POLICY_REPLAY_PARALLEL_BACKEND = "process"
OPTIMIZER_POLICY_REPLAY_DEDUP_BY_SIGNATURE = True
OPTIMIZER_POLICY_REPLAY_CONTEXT_REUSE_ENABLED = True

# Local-min diagnostics / safe evaluation ordering.
OPTIMIZER_LOCAL_MIN_DEPENDENCY_STATS_ENABLED = True
OPTIMIZER_LOCAL_MIN_PORTFOLIO_DEPENDENCY_ORDER = "last"
OPTIMIZER_LOCAL_MIN_SIGNAL_DEPENDENCY_FIELD_ORDER = "hard_fail_first"
# Shared / evaluation caches.
OPTIMIZER_ROLLING_SHARED_PREP_CACHE_MAX_ITEMS = 256
OPTIMIZER_FULL_EVAL_CACHE_MAX_ITEMS = 512

# Portfolio / active replay preparation workers.
OPTIMIZER_PORTFOLIO_PREP_WORKERS = "auto"
OPTIMIZER_PORTFOLIO_PREP_PARALLEL_MIN_TICKERS = 30
OPTIMIZER_PORTFOLIO_PREP_AUTO_MAX_WORKERS = 8
OPTIMIZER_ACTIVE_REPLAY_PREP_WORKERS = "auto"
OPTIMIZER_ACTIVE_REPLAY_PREP_AUTO_MAX_WORKERS = 8

# Optimizer runtime diagnostics / local execution caches.
OPTIMIZER_RAW_CACHE_LOCK_STALE_SEC = 6 * 60 * 60
OPTIMIZER_LOCAL_MIN_PROGRESS_MIN_INTERVAL_SEC = 1.0
OPTIMIZER_PROFILE_WRITE_FILES = True
OPTIMIZER_OUTER_ROLLING_PROFILE_WRITE_FILES = False
OPTIMIZER_OUTER_ROLLING_STUDY_STORAGE = "memory"
OPTIMIZER_RESOURCE_WRITE_CSV = False
OPTIMIZER_RESOURCE_SAMPLE_INTERVAL_SEC = 2.0
OPTIMIZER_RESOURCE_DISK_MBPS_CAP = 500.0

# Outer-rolling active replay execution strategy.
OPTIMIZER_ACTIVE_REPLAY_INCLUDE_TRADE_LOGS = False
OPTIMIZER_ACTIVE_REPLAY_INCLUDE_PIT_STATS_INDEX = True
OPTIMIZER_ACTIVE_REPLAY_USE_PREPARED_CACHE = False
OPTIMIZER_ACTIVE_REPLAY_WRITE_PREPARED_CACHE = False

